import fs from "fs";
import path from "path";

export interface UniqueSpiritualPlace {
  id: string;
  name: string;
  subtitle: string;
  icon: string;
  spiritualMeaning: string;
  description: string;
  biblicalReference: string;
  themes: string[];
  scriptureCountDisplay: string;
  isPublished: boolean;
  isFeatured?: boolean;
  displayOrder: number;
  colorGradient: string;
  badgeText: string;
  historicalContext: string;
}

// Master list of unique Biblical places with their authentic scriptural references and spiritual meanings
export const CANONICAL_UNIQUE_PLACES: Omit<UniqueSpiritualPlace, "displayOrder" | "isPublished" | "scriptureCountDisplay">[] = [
  // 1-50: Foundational & Patriarchal Sanctuaries
  {
    id: "rehoboth",
    name: "Rehoboth",
    subtitle: "A Place of Divine Room & Fruitfulness",
    icon: "🕊️",
    spiritualMeaning: "The turning point where strife and contention cease, and the Lord makes abundant room for your breakthrough and multiplication.",
    description: "After digging wells at Esek and Sitnah amidst contention, Isaac dug another well and they strove not for it. He called the name of it Rehoboth; and he said, 'For now the LORD hath made room for us, and we shall be fruitful in the land.'",
    biblicalReference: "Genesis 26:22",
    themes: ["Breakthrough", "Fruitfulness", "Peace", "Expansion", "Divine Favor"],
    colorGradient: "from-amber-600 via-yellow-700 to-indigo-950",
    badgeText: "Divine Room",
    historicalContext: "Located in the Negev desert southwest of Beersheba (modern Ruhaibeh), signifying spaciousness granted by God after long seasons of dispute."
  },
  {
    id: "esek",
    name: "Esek",
    subtitle: "Overcoming Contention & Striving",
    icon: "⚡",
    spiritualMeaning: "The place where the enemy contends over your blessings, teaching resilience, perseverance, and confidence in God's unending supply.",
    description: "Isaac's servants digged in the valley, and found there a well of springing water. And the herdmen of Gerar did strive with Isaac's herdmen, saying, The water is ours: and he called the name of the well Esek; because they strove with him.",
    biblicalReference: "Genesis 26:20",
    themes: ["Perseverance", "Overcoming Strife", "Spiritual Resilience", "Trust"],
    colorGradient: "from-orange-700 via-rose-900 to-slate-900",
    badgeText: "Contention",
    historicalContext: "A contested valley well in the territory of Gerar, representing the tests of opposition before divine expansion."
  },
  {
    id: "sitnah",
    name: "Sitnah",
    subtitle: "Triumphing Over Accusation & Enmity",
    icon: "🛡️",
    spiritualMeaning: "The place of hostility and accusation where you refuse bitterness, maintain spiritual integrity, and move forward toward God's promise.",
    description: "And they digged another well, and strove for that also: and he called the name of it Sitnah. Isaac refused to engage in carnal warfare, knowing God had greater territory ahead.",
    biblicalReference: "Genesis 26:21",
    themes: ["Patience", "Overcoming Accusation", "Spiritual Focus", "Integrity"],
    colorGradient: "from-red-800 via-purple-950 to-slate-900",
    badgeText: "Enmity",
    historicalContext: "A second contested well in the Negev, named from the root meaning 'adversary' or 'accusation'."
  },
  {
    id: "ebenezer",
    name: "Ebenezer",
    subtitle: "The Stone of Divine Help",
    icon: "🪨",
    spiritualMeaning: "A sacred landmark of thanksgiving declaring that through every battle, delay, and trial, the Lord has faithfully helped and sustained us.",
    description: "Then Samuel took a stone, and set it between Mizpeh and Shen, and called the name of it Ebenezer, saying, 'Hitherto hath the LORD helped us.' The Philistines were subdued and came no more into the coast of Israel.",
    biblicalReference: "1 Samuel 7:12",
    themes: ["Divine Help", "Thanksgiving", "Victory", "God's Faithfulness", "Remembrance"],
    colorGradient: "from-blue-900 via-slate-800 to-amber-900",
    badgeText: "Stone of Help",
    historicalContext: "A battlefield monument raised by Samuel between Mizpah and Shen following Israel's supernatural deliverance from the Philistines."
  },
  {
    id: "bethel",
    name: "Bethel",
    subtitle: "The House of God & Open Heavens",
    icon: "🪜",
    spiritualMeaning: "The consecrated ground of celestial revelation where the ladder between heaven and earth is revealed, and angels ascend and descend.",
    description: "Jacob lighted upon a certain place, and tarried there all night. He dreamed of a ladder set upon the earth, and the top of it reached to heaven: and behold the angels of God ascending and descending on it. And he said, 'Surely the LORD is in this place; and I knew it not.'",
    biblicalReference: "Genesis 28:10–19",
    themes: ["Open Heavens", "House of God", "Divine Encounter", "Angelic Ministry", "Covenant"],
    colorGradient: "from-indigo-900 via-blue-950 to-slate-900",
    badgeText: "House of God",
    historicalContext: "Formerly called Luz, situated in the hill country of Ephraim about 12 miles north of Jerusalem; Jacob built an altar here."
  },
  {
    id: "peniel",
    name: "Peniel",
    subtitle: "Face-to-Face Encounter & Transformation",
    icon: "✨",
    spiritualMeaning: "The wrestling ground where self-reliance is broken, face-to-face communion occurs, and your destiny and name are permanently transformed.",
    description: "Jacob was left alone; and there wrestled a man with him until the breaking of the day. And Jacob said, 'I will not let thee go, except thou bless me.' And he blessed him there, and Jacob named the place Peniel: 'For I have seen God face to face, and my life is preserved.'",
    biblicalReference: "Genesis 32:24–30",
    themes: ["Transformation", "Seeking God's Face", "Wrestling in Faith", "Identity", "Deliverance"],
    colorGradient: "from-purple-900 via-indigo-950 to-slate-900",
    badgeText: "Face of God",
    historicalContext: "Located along the Jabbok stream east of the Jordan River, where Jacob's name was changed to Israel."
  },
  {
    id: "el-bethel",
    name: "El Bethel",
    subtitle: "The God of the House of God",
    icon: "👑",
    spiritualMeaning: "Moving beyond spiritual experiences to a personal, intimate walk with the God of the sanctuary Himself.",
    description: "God said unto Jacob, Arise, go up to Bethel, and dwell there: and make there an altar unto God, that appeared unto thee when thou fleddest from the face of Esau thy brother. And he built there an altar, and called the place El-bethel.",
    biblicalReference: "Genesis 35:1–7",
    themes: ["Intimacy with God", "Holiness", "Consecration", "Altar of Worship"],
    colorGradient: "from-amber-700 via-slate-900 to-indigo-950",
    badgeText: "God of Bethel",
    historicalContext: "The altar site erected at Bethel by Jacob upon purifying his household and burying foreign gods under the oak of Shechem."
  },
  {
    id: "beersheba",
    name: "Beersheba",
    subtitle: "The Well of the Covenant Oath",
    icon: "💧",
    spiritualMeaning: "A sanctuary of unbreakable covenant promises, divine peace agreements, and generational inheritance.",
    description: "Abraham planted a grove in Beersheba, and called there on the name of the LORD, the everlasting God. There Isaac also re-dug the wells of his father and received God's blessing of generational multiplication.",
    biblicalReference: "Genesis 21:31–33; Genesis 26:33",
    themes: ["Covenant", "Generational Blessing", "Peace", "Everlasting God"],
    colorGradient: "from-cyan-900 via-blue-950 to-slate-900",
    badgeText: "Well of the Oath",
    historicalContext: "The southern boundary of the Promised Land, marking the ancient treaty between Abraham and Abimelech."
  },
  {
    id: "mizpah",
    name: "Mizpah",
    subtitle: "The Watchtower of Divine Oversight",
    icon: "👁️",
    spiritualMeaning: "A sacred watchtower where God watches over relationships, seals spiritual boundaries, and grants national repentance and victory.",
    description: "Laban and Jacob made a covenant and set up a heap of stones, and called it Mizpah; for he said, 'The LORD watch between me and thee, when we are absent one from another.'",
    biblicalReference: "Genesis 31:49; 1 Samuel 7:5–6",
    themes: ["Watchfulness", "Covenant Boundaries", "Spiritual Oversight", "Repentance"],
    colorGradient: "from-teal-900 via-slate-900 to-slate-950",
    badgeText: "Watchtower",
    historicalContext: "An elevated hill in Gilead where Jacob and Laban erected a heap of witness, later the gathering place of Samuel's national prayer assembly."
  },
  {
    id: "mahanaim",
    name: "Mahanaim",
    subtitle: "Two Camps of Angelic Encampment",
    icon: "⚔️",
    spiritualMeaning: "The revelation that wherever you go in God's will, heavenly hosts are encamped alongside your earthly journey.",
    description: "Jacob went on his way, and the angels of God met him. And when Jacob saw them, he said, 'This is God's host': and he called the name of that place Mahanaim (Two Camps).",
    biblicalReference: "Genesis 32:1–2",
    themes: ["Angelic Protection", "Heavenly Host", "Spiritual Warfare", "Divine Defense"],
    colorGradient: "from-indigo-900 via-violet-950 to-slate-900",
    badgeText: "Two Camps",
    historicalContext: "A strategic fortified city north of the Jabbok in Gilead, assigned to the Levites and later a city of refuge."
  },
  {
    id: "succoth",
    name: "Succoth",
    subtitle: "Shelters of Divine Protection & Rest",
    icon: "⛺",
    spiritualMeaning: "The place of transitional shelter, peace, and spiritual consolidation after intense seasons of struggle.",
    description: "Jacob journeyed to Succoth, and built him an house, and made booths for his cattle: therefore the name of the place is called Succoth (Booths).",
    biblicalReference: "Genesis 33:17; Psalm 60:6",
    themes: ["Rest", "Divine Protection", "Consolidation", "Family Provision"],
    colorGradient: "from-amber-800 via-stone-900 to-slate-900",
    badgeText: "Booths / Shelters",
    historicalContext: "Located in the Jordan Valley near the mouth of the Jabbok river, where Jacob found rest after reconciling with Esau."
  },
  {
    id: "el-elohe-israel",
    name: "El Elohe Israel",
    subtitle: "God, the Personal God of Israel",
    icon: "🌟",
    spiritualMeaning: "The altar of personal claiming, where God is no longer merely the God of your fathers, but YOUR personal God and defender.",
    description: "Jacob erected there an altar, and called it El-elohe-Israel, establishing the testimony that God had personally redeemed him and become his strength.",
    biblicalReference: "Genesis 33:20",
    themes: ["Personal Faith", "Altar of Devotion", "Identity in God", "Worship"],
    colorGradient: "from-purple-900 via-amber-950 to-slate-900",
    badgeText: "God of Israel",
    historicalContext: "An altar built on the parcel of ground Jacob bought before Shechem from the children of Hamor."
  },
  {
    id: "zoar",
    name: "Zoar",
    subtitle: "The Place of Refuge in Judgment",
    icon: "🕊️",
    spiritualMeaning: "A sanctuary of divine mercy where small, seemingly insignificant places become mighty shelters of deliverance from surrounding calamity.",
    description: "Lot pleaded, 'Behold now, this city is near to flee unto, and it is a little one: Oh, let me escape thither, (is it not a little one?) and my soul shall live.' And the angel spared the city for his sake.",
    biblicalReference: "Genesis 19:20–22",
    themes: ["Divine Mercy", "Refuge", "Escape", "Supernatural Deliverance"],
    colorGradient: "from-rose-900 via-slate-900 to-indigo-950",
    badgeText: "Place of Refuge",
    historicalContext: "One of the five cities of the plain, spared from the destruction of Sodom and Gomorrah as a refuge for Lot."
  },
  {
    id: "jehovah-jireh",
    name: "Jehovah Jireh",
    subtitle: "The Mount of Supernatural Provision",
    icon: "🐏",
    spiritualMeaning: "The summit of obedience where God reveals that before you even arrive at the place of sacrifice, His provision is already prepared.",
    description: "Abraham lifted up his eyes, and looked, and behold behind him a ram caught in a thicket by his horns: and Abraham went and took the ram, and offered him up for a burnt offering in the stead of his son. And Abraham called the name of that place Jehovah-jireh: as it is said to this day, 'In the mount of the LORD it shall be seen.'",
    biblicalReference: "Genesis 22:13–14",
    themes: ["Supernatural Provision", "Obedience", "Mount Moriah", "Covenant Sacrifice"],
    colorGradient: "from-amber-600 via-yellow-800 to-slate-900",
    badgeText: "The Lord Will Provide",
    historicalContext: "Mount Moriah in Jerusalem, where Abraham's ultimate test of obedience foreshadowed Christ's sacrifice on Calvary."
  },
  {
    id: "marah",
    name: "Marah",
    subtitle: "Sweetening the Bitter Waters",
    icon: "🌿",
    spiritualMeaning: "The place where God reveals His healing power, turning the bitter disappointments of life into fountains of spiritual sweetness through the Cross.",
    description: "When they came to Marah, they could not drink of the waters of Marah, for they were bitter: therefore the name of it was called Marah. Moses cried unto the LORD; and the LORD shewed him a tree, which when he had cast into the waters, the waters were made sweet: there he made for them a statute and an ordinance, and there he proved them.",
    biblicalReference: "Exodus 15:23–25",
    themes: ["Divine Healing", "Overcoming Bitterness", "The Power of the Cross", "Testing"],
    colorGradient: "from-emerald-800 via-teal-950 to-slate-900",
    badgeText: "Sweetened Waters",
    historicalContext: "A desert encampment in the Wilderness of Shur where bitter saline springs were miraculously made potable."
  },
  {
    id: "elim",
    name: "Elim",
    subtitle: "Twelve Wells & Seventy Palm Trees",
    icon: "🌴",
    spiritualMeaning: "The oasis of abundant spiritual refreshment, governmental order, and fruitful shade after crossing desert trials.",
    description: "And they came to Elim, where were twelve wells of water, and threescore and ten palm trees: and they encamped there by the waters.",
    biblicalReference: "Exodus 15:27",
    themes: ["Spiritual Refreshment", "Abundance", "Oasis of Rest", "Divine Replenishment"],
    colorGradient: "from-teal-800 via-emerald-950 to-slate-900",
    badgeText: "Oasis of Palms",
    historicalContext: "A lush oasis identified with Wadi Gharandel in the Sinai Peninsula, providing abundant fresh water and shelter."
  },
  {
    id: "massah",
    name: "Massah",
    subtitle: "The Place of Testing & Faith",
    icon: "🔥",
    spiritualMeaning: "The desert trial where faith is tested, reminding us never to doubt God's presence or question His faithfulness in dry seasons.",
    description: "He called the name of the place Massah (Temptation/Testing), and Meribah (Chiding), because of the chiding of the children of Israel, and because they tempted the LORD, saying, 'Is the LORD among us, or not?'",
    biblicalReference: "Exodus 17:7; Deuteronomy 6:16",
    themes: ["Faith in the Wilderness", "Trusting God", "Testing", "Spiritual Endurance"],
    colorGradient: "from-orange-800 via-stone-900 to-slate-900",
    badgeText: "Testing",
    historicalContext: "A desert station near Rephidim where the people thirsted and demanded water from Moses."
  },
  {
    id: "meribah",
    name: "Meribah",
    subtitle: "Water from the Smitten Rock",
    icon: "🌊",
    spiritualMeaning: "The place where God responds to human weakness and complaint with supernatural grace, bringing streams of living water from the hardest rock.",
    description: "Moses struck the rock with the rod of God in Horeb, and water gushed out abundantly for the congregation and their beasts to drink.",
    biblicalReference: "Exodus 17:6–7; Numbers 20:13; Psalm 81:7",
    themes: ["Living Waters", "Smitten Rock", "Grace in Crisis", "Supernatural Supply"],
    colorGradient: "from-cyan-800 via-blue-950 to-slate-900",
    badgeText: "Water from the Rock",
    historicalContext: "The rock in Horeb where God commanded Moses to strike the granite cliff, releasing torrential streams."
  },
  {
    id: "jehovah-nissi",
    name: "Jehovah Nissi",
    subtitle: "The Lord Is My Victorious Banner",
    icon: "🚩",
    spiritualMeaning: "The battle ground where uplifted hands of prayer and intercession secure total triumph over spiritual adversaries.",
    description: "When Moses held up his hand, Israel prevailed: and when he let down his hand, Amalek prevailed. Aaron and Hur stayed up his hands, and Joshua discomfited Amalek. And Moses built an altar, and called the name of it Jehovah-nissi: 'The LORD is my banner.'",
    biblicalReference: "Exodus 17:11–15",
    themes: ["Spiritual Warfare", "Intercession", "Victory Banner", "Triumph in Prayer"],
    colorGradient: "from-red-700 via-amber-950 to-slate-900",
    badgeText: "The Lord My Banner",
    historicalContext: "The battlefield altar at Rephidim following the miraculous defeat of Amalek through intercessory posture."
  },
  {
    id: "mount-sinai",
    name: "Mount Sinai",
    subtitle: "The Mountain of Holy Law & Glory",
    icon: "⚡",
    spiritualMeaning: "The awe-inspiring mountain of divine presence, thunder, holy fire, and the establishment of God's righteous law and covenant.",
    description: "Mount Sinai was altogether on a smoke, because the LORD descended upon it in fire: and the smoke thereof ascended as the smoke of a furnace, and the whole mount quaked greatly. And the LORD called Moses up to the top of the mount; and Moses went up.",
    biblicalReference: "Exodus 19:16–20; Exodus 20:1–17",
    themes: ["Holy Presence", "Divine Covenant", "Righteous Law", "Awe of God"],
    colorGradient: "from-amber-600 via-red-950 to-slate-950",
    badgeText: "Mountain of Glory",
    historicalContext: "The rugged granite peaks in the southern Sinai peninsula (Jebel Musa) where the Ten Commandments were delivered."
  },
  {
    id: "jehovah-shalom",
    name: "Jehovah Shalom",
    subtitle: "The Altar of Supernatural Peace",
    icon: "🕊️",
    spiritualMeaning: "The altar where fear is extinguished by the revelation that the Lord is our Peace, commissioning mighty deliverers to destroy idolatry.",
    description: "The LORD said unto Gideon, 'Peace be unto thee; fear not: thou shalt not die.' Then Gideon built an altar there unto the LORD, and called it Jehovah-shalom: unto this day it is yet in Ophrah of the Abi-ezrites.",
    biblicalReference: "Judges 6:23–24",
    themes: ["Supernatural Peace", "Overcoming Fear", "Divine Commission", "Worship"],
    colorGradient: "from-blue-800 via-teal-950 to-slate-900",
    badgeText: "The Lord Is Peace",
    historicalContext: "An altar built by Gideon at Ophrah after encountering the Angel of the Lord under the terebinth tree."
  },
  {
    id: "bochim",
    name: "Bochim",
    subtitle: "The Place of Weepers & Brokenness",
    icon: "💧",
    spiritualMeaning: "The place of sacred repentance, brokenness before God, and re-consecration where tears of remorse turn into renewed obedience.",
    description: "The angel of the LORD came up from Gilgal to Bochim, and convicted the people. When the angel spake these words unto all the children of Israel, the people lifted up their voice, and wept. And they called the name of that place Bochim: and they sacrificed there unto the LORD.",
    biblicalReference: "Judges 2:1–5",
    themes: ["Repentance", "Brokenness", "Spiritual Renewal", "Consecration"],
    colorGradient: "from-slate-700 via-indigo-950 to-slate-950",
    badgeText: "Place of Weeping",
    historicalContext: "An unidentified site near Shiloh or Bethel where the assembly of Israel wept over compromise and renewed their sacrifices."
  },
  {
    id: "gilgal",
    name: "Gilgal",
    subtitle: "Rolling Away the Reproach of Egypt",
    icon: "⭕",
    spiritualMeaning: "The consecrated camp of circumcision, Passover celebration, and total eradication of past shame, slavery, and generational reproach.",
    description: "The LORD said unto Joshua, 'This day have I rolled away the reproach of Egypt from off you.' Wherefore the name of the place is called Gilgal unto this day. And the children of Israel encamped in Gilgal, and kept the passover.",
    biblicalReference: "Joshua 5:9–10",
    themes: ["Rolling Away Reproach", "New Beginning", "Covenant Circumcision", "Passover Victory"],
    colorGradient: "from-amber-700 via-rose-950 to-slate-900",
    badgeText: "Reproach Rolled Away",
    historicalContext: "Israel's first headquarters west of the Jordan River in the plains of Jericho, marked by twelve memorial stones taken from the dry riverbed."
  },
  {
    id: "valley-of-achor",
    name: "Valley of Achor",
    subtitle: "The Door of Hope in Trouble",
    icon: "🚪",
    spiritualMeaning: "The place where past hidden sin and trouble are judged and purged, transforming your deepest valley of failure into a radiant door of hope.",
    description: "And I will give her her vineyards from thence, and the valley of Achor for a door of hope: and she shall sing there, as in the days of her youth, and as in the day when she came up out of the land of Egypt.",
    biblicalReference: "Joshua 7:24–26; Hosea 2:15",
    themes: ["Door of Hope", "Purification", "Restoration", "Singing After Sorrow"],
    colorGradient: "from-violet-900 via-rose-950 to-slate-900",
    badgeText: "Door of Hope",
    historicalContext: "A valley north of Jericho where Achan's sin was judged, later prophesied by Hosea as the gateway of messianic restoration."
  },
  {
    id: "lo-debar",
    name: "Lo Debar",
    subtitle: "From Desolation to the King's Table",
    icon: "👑",
    spiritualMeaning: "The dry, forgotten place of obscurity where the King's covenant kindness seeks you out, restoring all lost inheritance and royal dignity.",
    description: "David said, 'Is there yet any that is left of the house of Saul, that I may shew him kindness for Jonathan's sake?' And they found Mephibosheth in Lo-debar, and brought him to the king's palace to eat at the royal table continually.",
    biblicalReference: "2 Samuel 9:1–13",
    themes: ["Covenant Mercy", "Restoration", "Royal Honor", "Grace over Disability"],
    colorGradient: "from-indigo-900 via-amber-950 to-slate-900",
    badgeText: "Covenant Kindness",
    historicalContext: "A barren border town in Gilead east of the Jordan, literally meaning 'no pasture' or 'place of silence'."
  },
  {
    id: "baal-perazim",
    name: "Baal Perazim",
    subtitle: "The Master of Breakthroughs",
    icon: "🌊",
    spiritualMeaning: "The battleground where God breaks through your enemies and limitations like the sudden, unstoppable breach of surging floodwaters.",
    description: "David came to Baal-perazim, and David smote them there, and said, 'The LORD hath broken forth upon mine enemies before me, as the breach of waters.' Therefore he called the name of that place Baal-perazim.",
    biblicalReference: "2 Samuel 5:20; 1 Chronicles 14:11",
    themes: ["Breakthrough", "Overwhelming Victory", "Breach of Waters", "Divine Momentum"],
    colorGradient: "from-blue-700 via-cyan-950 to-slate-950",
    badgeText: "Master of Breakthrough",
    historicalContext: "A hill near the Valley of Rephaim south of Jerusalem where David broke the Philistine siege."
  },
  {
    id: "perez-uzzah",
    name: "Perez Uzzah",
    subtitle: "The Reverence of God's Holiness",
    icon: "⚡",
    spiritualMeaning: "A solemn reminder to handle sacred things according to divine order, reverence, and spiritual consecration rather than human convenience.",
    description: "And the anger of the LORD was kindled against Uzzah, and God smote him there for his error; and there he died by the ark of God. And David called the name of the place Perez-uzzah.",
    biblicalReference: "2 Samuel 6:6–8; 1 Chronicles 13:11",
    themes: ["Holiness", "Divine Order", "Reverence", "Ark of God"],
    colorGradient: "from-red-900 via-stone-900 to-slate-950",
    badgeText: "Divine Reverence",
    historicalContext: "The threshing floor of Nachon along the route from Kiriath-jearim to Jerusalem."
  },
  {
    id: "hebron",
    name: "Hebron",
    subtitle: "Sanctuary of Fellowship & Royal Anointing",
    icon: "👑",
    spiritualMeaning: "The ancient city of covenant friendship with God, patriarch tombs, and the place where David was anointed king over Judah and Israel.",
    description: "So all the elders of Israel came to the king to Hebron; and king David made a league with them in Hebron before the LORD: and they anointed David king over Israel.",
    biblicalReference: "Genesis 13:18; 2 Samuel 2:1–4; 2 Samuel 5:3",
    themes: ["Royal Anointing", "Fellowship with God", "Kingdom Authority", "Covenant Heritage"],
    colorGradient: "from-amber-700 via-purple-950 to-slate-900",
    badgeText: "Royal Fellowship",
    historicalContext: "The elevated hill city in Judah (Kirjath-arba) containing the cave of Machpelah; David's capital for his first 7 years."
  },
  {
    id: "shiloh",
    name: "Shiloh",
    subtitle: "The Tabernacle of Persistent Prayer",
    icon: "🔥",
    spiritualMeaning: "The sacred resting place of the Ark where Hannah poured out her soul in tears and received Samuel, transforming national destiny.",
    description: "And the whole congregation of the children of Israel assembled together at Shiloh, and set up the tabernacle of the congregation there. There Hannah prayed in bitterness of soul, and the Lord remembered her.",
    biblicalReference: "Joshua 18:1; 1 Samuel 1:9–20",
    themes: ["Answered Prayer", "Tabernacle Worship", "Pouring Out the Soul", "Divine Remembrance"],
    colorGradient: "from-rose-800 via-indigo-950 to-slate-900",
    badgeText: "Place of Prayer",
    historicalContext: "The central religious sanctuary of Israel in Ephraim for over three centuries prior to Jerusalem."
  },
  {
    id: "ramah",
    name: "Ramah",
    subtitle: "The Prophet's Watch & School of Glory",
    icon: "📜",
    spiritualMeaning: "The prophetic heights where prayer, spiritual mentorship, and the contagious atmosphere of the Holy Spirit neutralize every enemy assault.",
    description: "David fled, and came to Samuel to Ramah, and told him all that Saul had done to him. And when Saul sent messengers to take David, the Spirit of God came upon them, and they prophesied also.",
    biblicalReference: "1 Samuel 19:18–24; 1 Samuel 25:1",
    themes: ["Prophetic Atmosphere", "Holy Spirit Presence", "Spiritual Mentorship", "Defense"],
    colorGradient: "from-violet-800 via-slate-900 to-indigo-950",
    badgeText: "Prophetic Heights",
    historicalContext: "Samuel's hometown and prophetic academy (Naioth in Ramah) in the hills of Benjamin."
  },
  {
    id: "bethany",
    name: "Bethany",
    subtitle: "The House of Resurrection & Devotion",
    icon: "🌿",
    spiritualMeaning: "The beloved haven of intimacy where Mary sat at Jesus' feet, poured out costly spikenard, and where Lazarus walked out of the grave.",
    description: "Jesus came to Bethany, where Lazarus was which had been dead, whom he raised from the dead. There they made him a supper; and Martha served: but Lazarus was one of them that sat at the table with him. Then took Mary a pound of ointment of spikenard, very costly, and anointed the feet of Jesus.",
    biblicalReference: "John 11:1–44; John 12:1–8",
    themes: ["Resurrection Life", "Costly Worship", "Intimate Fellowship", "Miracles"],
    colorGradient: "from-amber-600 via-rose-950 to-slate-900",
    badgeText: "House of Devotion",
    historicalContext: "A tranquil village on the eastern slope of the Mount of Olives, two miles from Jerusalem."
  },
  {
    id: "capernaum",
    name: "Capernaum",
    subtitle: "The City of Signs & Wonders",
    icon: "✨",
    spiritualMeaning: "The earthly ministry headquarters of Christ where paralyzed men were lowered through roofs, centurions exercised great faith, and demons fled.",
    description: "And leaving Nazareth, he came and dwelt in Capernaum, which is upon the sea coast... The people which sat in darkness saw great light; and to them which sat in the region and shadow of death light is sprung up.",
    biblicalReference: "Matthew 4:13–16; Mark 2:1–12; Luke 4:31–37",
    themes: ["Healing Miracles", "Authority in Preaching", "Faith", "Great Light"],
    colorGradient: "from-blue-700 via-indigo-950 to-slate-900",
    badgeText: "City of Wonders",
    historicalContext: "A bustling fishing town on the northwest shore of the Sea of Galilee."
  },
  {
    id: "emmaus",
    name: "Emmaus",
    subtitle: "Hearts Burning on the Resurrection Road",
    icon: "📖",
    spiritualMeaning: "The seven-mile journey where the risen Christ walks with weary disciples, opens the Scriptures, and makes hearts burn with holy revelation.",
    description: "And their eyes were opened, and they knew him; and he vanished out of their sight. And they said one to another, 'Did not our heart burn within us, while he talked with us by the way, and while he opened to us the scriptures?'",
    biblicalReference: "Luke 24:13–35",
    themes: ["Burning Hearts", "Scriptural Illumination", "Risen Christ", "Bread of Fellowship"],
    colorGradient: "from-amber-700 via-orange-950 to-slate-900",
    badgeText: "Burning Hearts",
    historicalContext: "A village located about 60 stadia (7 miles) west of Jerusalem."
  },
  {
    id: "golgotha",
    name: "Golgotha",
    subtitle: "The Place of Ultimate Redemption",
    icon: "✝️",
    spiritualMeaning: "The skull hill outside the gate where Jesus bore the curse of sin, shed His precious blood, tore the veil in two, and declared 'It is finished!'",
    description: "And when they were come to the place, which is called Calvary (Golgotha), there they crucified him... Jesus cried with a loud voice, and gave up the ghost. And the veil of the temple was rent in twain from the top to the bottom.",
    biblicalReference: "Matthew 27:33; Luke 23:33; John 19:17–30",
    themes: ["Atonement", "Redemption", "The Cross", "Finished Work", "Victory over Sin"],
    colorGradient: "from-red-900 via-rose-950 to-slate-950",
    badgeText: "Calvary / Redemption",
    historicalContext: "The rocky knoll outside the walls of Jerusalem where Roman crucifixions took place."
  },
  {
    id: "gethsemane",
    name: "Gethsemane",
    subtitle: "The Olive Press of Total Surrender",
    icon: "🫒",
    spiritualMeaning: "The garden of agonizing prayer where human will completely yields to the Father's sovereign plan: 'Not my will, but Thine be done.'",
    description: "Then cometh Jesus with them unto a place called Gethsemane, and saith unto the disciples, 'Sit ye here, while I go and pray yonder.' And being in an agony he prayed more earnestly: and his sweat was as it were great drops of blood falling down to the ground.",
    biblicalReference: "Matthew 26:36–46; Luke 22:39–46",
    themes: ["Surrender", "Yieldedness", "Earnest Intercession", "Triumph in Weakness"],
    colorGradient: "from-emerald-900 via-stone-900 to-slate-950",
    badgeText: "Total Surrender",
    historicalContext: "An olive orchard and oil press situated at the foot of the Mount of Olives across the Kidron brook."
  },
  {
    id: "isle-of-patmos",
    name: "Patmos",
    subtitle: "The Isle of Apocalyptic Revelation",
    icon: "👁️",
    spiritualMeaning: "The isolated penal island where physical confinement cannot stop the glory of heaven from unveiling the glorified Son of God.",
    description: "I John, who also am your brother, and companion in tribulation... was in the isle that is called Patmos, for the word of God, and for the testimony of Jesus Christ. I was in the Spirit on the Lord's day, and heard behind me a great voice, as of a trumpet.",
    biblicalReference: "Revelation 1:9–18",
    themes: ["Apocalyptic Vision", "In the Spirit", "Glorified Christ", "Triumph in Exile"],
    colorGradient: "from-purple-950 via-indigo-900 to-slate-900",
    badgeText: "Heaven Unveiled",
    historicalContext: "A volcanic Greek island in the Aegean Sea used by the Roman Empire as a place of banishment."
  },
  {
    id: "antioch",
    name: "Antioch of Syria",
    subtitle: "The Missionary Launchpad of the Nations",
    icon: "🌍",
    spiritualMeaning: "The dynamic apostolic community of multi-ethnic unity, Spirit-directed fasting, and the cradle where believers were first called Christians.",
    description: "And the disciples were called Christians first in Antioch. As they ministered to the Lord, and fasted, the Holy Ghost said, 'Separate me Barnabas and Saul for the work whereunto I have called them.' And when they had fasted and prayed, and laid their hands on them, they sent them away.",
    biblicalReference: "Acts 11:19–26; Acts 13:1–3",
    themes: ["Missions", "Apostolic Sending", "Prophetic Worship", "Christian Identity"],
    colorGradient: "from-blue-800 via-cyan-950 to-slate-900",
    badgeText: "Apostolic Launchpad",
    historicalContext: "The third largest city of the Roman Empire, situated on the Orontes River, serving as the mother church of Gentile missions."
  },
  {
    id: "berea",
    name: "Berea",
    subtitle: "The Noble Search of the Scriptures",
    icon: "📜",
    spiritualMeaning: "The standard of spiritual nobility where believers receive the word with all readiness of mind and search the Scriptures daily.",
    description: "These were more noble than those in Thessalonica, in that they received the word with all readiness of mind, and searched the scriptures daily, whether those things were so. Therefore many of them believed.",
    biblicalReference: "Acts 17:10–12",
    themes: ["Nobility in Scripture", "Daily Bible Study", "Discernment", "Unshakable Faith"],
    colorGradient: "from-amber-800 via-stone-900 to-slate-900",
    badgeText: "Noble Bereans",
    historicalContext: "A prosperous city in southwestern Macedonia at the foot of Mount Bermion."
  },
  {
    id: "philippi",
    name: "Philippi",
    subtitle: "Midnight Praises & Shattered Chains",
    icon: "⛓️",
    spiritualMeaning: "The inner prison where midnight worship triggers celestial earthquakes, breaks all chains, opens all doors, and leads household captives to Christ.",
    description: "And at midnight Paul and Silas prayed, and sang praises unto God: and the prisoners heard them. And suddenly there was a great earthquake, so that the foundations of the prison were shaken: and immediately all the doors were opened, and every one's bands were loosed.",
    biblicalReference: "Acts 16:12–40; Philippians 4:4–13",
    themes: ["Midnight Praise", "Earthquake Breakthrough", "Chains Loosed", "Rejoicing Always"],
    colorGradient: "from-indigo-800 via-purple-950 to-slate-900",
    badgeText: "Midnight Praise",
    historicalContext: "A Roman colony in eastern Macedonia where the first church on European soil was planted."
  },
  {
    id: "thessalonica",
    name: "Thessalonica",
    subtitle: "Turning the World Upside Down",
    icon: "🔥",
    spiritualMeaning: "The fearless testimony that turns pagan culture upside down, producing work of faith, labor of love, and patience of hope.",
    description: "These that have turned the world upside down are come hither also... For from you sounded out the word of the Lord not only in Macedonia and Achaia, but also in every place your faith to God-ward is spread abroad.",
    biblicalReference: "Acts 17:1–9; 1 Thessalonians 1:3–8",
    themes: ["Transforming Culture", "Bold Witness", "Faithful Labor", "Sounding the Word"],
    colorGradient: "from-cyan-900 via-blue-950 to-slate-900",
    badgeText: "Sounding Forth",
    historicalContext: "The capital and major seaport of the Roman province of Macedonia on the Thermaic Gulf."
  },
  {
    id: "corinth",
    name: "Corinth",
    subtitle: "Grace in the Cross & Spiritual Gifts",
    icon: "🏛️",
    spiritualMeaning: "The metropolitan crossroads where divine grace triumphs over worldly corruption, manifesting spiritual gifts and the supreme way of agape love.",
    description: "Then spake the Lord to Paul in the night by a vision, 'Be not afraid, but speak, and hold not thy peace: For I am with thee, and no man shall set on thee to hurt thee: for I have much people in this city.'",
    biblicalReference: "Acts 18:1–11; 1 Corinthians 1:18; 1 Corinthians 13",
    themes: ["Courage in Ministry", "Power of the Cross", "Spiritual Gifts", "Agape Love"],
    colorGradient: "from-amber-700 via-indigo-950 to-slate-900",
    badgeText: "Gifts & Grace",
    historicalContext: "A wealthy, cosmopolitan commercial hub on the narrow isthmus connecting mainland Greece with the Peloponnese."
  },
  {
    id: "ephesus",
    name: "Ephesus",
    subtitle: "The Armor of God & Apostolic Power",
    icon: "🛡️",
    spiritualMeaning: "The center of extraordinary miracles, triumph over occult powers, heavenly seatings in Christ, and whole armor of God.",
    description: "And God wrought special miracles by the hands of Paul: So that from his body were brought unto the sick handkerchiefs or aprons, and the diseases departed from them, and the evil spirits went out of them. So mightily grew the word of God and prevailed.",
    biblicalReference: "Acts 19:1–20; Ephesians 1:3; Ephesians 6:10–18",
    themes: ["Spiritual Armor", "Special Miracles", "Heavenly Places", "Prevailing Word"],
    colorGradient: "from-blue-900 via-slate-800 to-indigo-950",
    badgeText: "Apostolic Armor",
    historicalContext: "The leading metropolis of the Roman province of Asia, home to the Temple of Artemis and a major early Christian hub."
  },
  {
    id: "colossae",
    name: "Colossae",
    subtitle: "Christ the Preeminent Mystery of Glory",
    icon: "👑",
    spiritualMeaning: "The revelation of the supremacy of Christ over all principalities and powers, in whom dwells all the fullness of the Godhead bodily.",
    description: "For in him dwelleth all the fullness of the Godhead bodily. And ye are complete in him, which is the head of all principality and power... Christ in you, the hope of glory.",
    biblicalReference: "Colossians 1:15–27; Colossians 2:9–15",
    themes: ["Supremacy of Christ", "Christ in You", "Complete in Him", "Hope of Glory"],
    colorGradient: "from-purple-900 via-amber-950 to-slate-900",
    badgeText: "Christ Preeminent",
    historicalContext: "An ancient Phrygian city in the Lycus River valley of Asia Minor, near Laodicea and Hierapolis."
  },
  {
    id: "athens-areopagus",
    name: "Athens (Areopagus)",
    subtitle: "Declaring the True God to the Nations",
    icon: "🏛️",
    spiritualMeaning: "Standing on the highest intellectual and philosophical platforms to proclaim the Creator God in whom we live, move, and have our being.",
    description: "Then Paul stood in the midst of Mars' hill, and said, 'Ye men of Athens, I perceive that in all things ye are too superstitious. For as I passed by, I found an altar with this inscription, TO THE UNKNOWN GOD. Whom therefore ye ignorantly worship, him declare I unto you.'",
    biblicalReference: "Acts 17:22–34",
    themes: ["Bold Apologetics", "In Him We Live", "Resurrection Truth", "Declaration"],
    colorGradient: "from-teal-900 via-slate-900 to-slate-950",
    badgeText: "Mars' Hill",
    historicalContext: "The prominent rocky hill northwest of the Acropolis in Athens where the supreme council met."
  },
  {
    id: "rome-mamertine",
    name: "Rome",
    subtitle: "Unstoppable Gospel in the Empire's Heart",
    icon: "🏛️",
    spiritualMeaning: "The triumphant finish of the apostolic race, proclaiming the Kingdom of God with all confidence, no man forbidding it.",
    description: "Paul dwelt two whole years in his own hired house, and received all that came in unto him, Preaching the kingdom of God, and teaching those things which concern the Lord Jesus Christ, with all confidence, no man forbidding him.",
    biblicalReference: "Acts 28:30–31; 2 Timothy 4:6–8",
    themes: ["Unstoppable Gospel", "Finishing the Race", "Crown of Righteousness", "Kingdom Boldness"],
    colorGradient: "from-red-950 via-slate-900 to-amber-950",
    badgeText: "Imperial Witness",
    historicalContext: "The capital of the Roman Empire where both Paul and Peter laid down their lives as martyrs for Christ."
  },
  {
    id: "mount-carmel",
    name: "Mount Carmel",
    subtitle: "The Fire of God Falls on the Altar",
    icon: "🔥",
    spiritualMeaning: "The showdown summit where the repaired altar of God attracts divine fire, obliterating false idols and releasing abundance of rain.",
    description: "Elijah repaired the altar of the LORD that was broken down. Then the fire of the LORD fell, and consumed the burnt sacrifice, and the wood, and the stones, and the dust, and licked up the water that was in the trench. And when all the people saw it, they fell on their faces: and they said, 'The LORD, he is the God!'",
    biblicalReference: "1 Kings 18:20–46",
    themes: ["Consuming Fire", "Repaired Altar", "Overcoming Idolatry", "Abundance of Rain"],
    colorGradient: "from-amber-600 via-red-950 to-slate-950",
    badgeText: "Fire on the Altar",
    historicalContext: "A coastal mountain range in northern Israel overlooking the Mediterranean Sea and the Jezreel Valley."
  },
  {
    id: "mount-hermon",
    name: "Mount Hermon",
    subtitle: "The Dew of Unity & Commanded Blessing",
    icon: "🏔️",
    spiritualMeaning: "The snow-capped summit representing spiritual unity among brethren, where the Lord commands the blessing, even life forevermore.",
    description: "Behold, how good and how pleasant it is for brethren to dwell together in unity! As the dew of Hermon, and as the dew that descended upon the mountains of Zion: for there the LORD commanded the blessing, even life for evermore.",
    biblicalReference: "Psalm 133:1–3",
    themes: ["Spiritual Unity", "Commanded Blessing", "Heavenly Dew", "Brothers in Accord"],
    colorGradient: "from-cyan-900 via-blue-950 to-slate-900",
    badgeText: "Commanded Blessing",
    historicalContext: "The highest mountain cluster in the Anti-Lebanon range, straddling the northern border of Israel."
  },
  {
    id: "mount-moriah",
    name: "Mount Moriah",
    subtitle: "The Foundation of the Holy Temple",
    icon: "🏛️",
    spiritualMeaning: "The sacred ridge of sacrificial obedience where Solomon built the Temple and God's Shekinah glory filled the sanctuary.",
    description: "Then Solomon began to build the house of the LORD at Jerusalem in mount Moriah, where the LORD appeared unto David his father, in the place that David had prepared in the threshingfloor of Ornan the Jebusite.",
    biblicalReference: "Genesis 22:2; 2 Chronicles 3:1",
    themes: ["Shekinah Glory", "Sacred Temple", "Permanent Dwelling", "Altar of Worship"],
    colorGradient: "from-amber-600 via-yellow-900 to-indigo-950",
    badgeText: "Temple Mountain",
    historicalContext: "The elevated rocky ridge in Jerusalem encompassing the Temple Mount and the ancient threshing floor of Araunah."
  },
  {
    id: "mount-horeb",
    name: "Mount Horeb",
    subtitle: "The Burning Bush & Still Small Voice",
    icon: "🔥",
    spiritualMeaning: "The mountain of divine revelation where holy bushes burn unconsumed and God speaks in the gentle, still small whisper of grace.",
    description: "Moses led the flock to the backside of the desert, and came to the mountain of God, even to Horeb. And the angel of the LORD appeared unto him in a flame of fire out of the midst of a bush: and he looked, and, behold, the bush burned with fire, and the bush was not consumed.",
    biblicalReference: "Exodus 3:1–5; 1 Kings 19:8–12",
    themes: ["Holy Ground", "Burning Bush", "Still Small Voice", "Divine Calling"],
    colorGradient: "from-orange-700 via-rose-950 to-slate-900",
    badgeText: "Burning Bush",
    historicalContext: "Another biblical name for the Sinai mountain range, associated with both Moses' call and Elijah's divine encounter."
  },
  {
    id: "mount-nebo",
    name: "Mount Nebo (Pisgah)",
    subtitle: "The Summit of Prophetic Vision",
    icon: "👁️",
    spiritualMeaning: "The panoramic peak where God grants supernatural spiritual vision to behold the full scope of generational inheritance.",
    description: "Moses went up from the plains of Moab unto the mountain of Nebo, to the top of Pisgah, that is over against Jericho. And the LORD shewed him all the land of Gilead, unto Dan, and all Naphtali, and the land of Ephraim... unto the utmost sea.",
    biblicalReference: "Deuteronomy 34:1–4",
    themes: ["Prophetic Vision", "Generational Promise", "Seeing by Faith", "Promised Land"],
    colorGradient: "from-indigo-900 via-blue-950 to-slate-900",
    badgeText: "Vision Peak",
    historicalContext: "An elevated ridge in modern Jordan overlooking the Dead Sea, the Jordan Valley, and the hills of Judea."
  }
];

console.log("Canonical unique places prepared:", CANONICAL_UNIQUE_PLACES.length);
