const fs = require('fs');
const path = require('path');

// 307 Raw Scripture References from Bismark Twum
const RAW_SCRIPTURES = [
  // OT (1-123)
  { num: 1, ref: "Genesis 1:28", theme: "Kingdom Dominion & Fruitfulness", isNew: false },
  { num: 2, ref: "Exodus 19:5", theme: "Covenant Treasure & Holy Obedience", isNew: false },
  { num: 3, ref: "Exodus 33:14", theme: "Unfailing Presence & Divine Rest", isNew: false },
  { num: 4, ref: "Leviticus 5:17", theme: "Holy Reverence & Heart Purity", isNew: true },
  { num: 5, ref: "Numbers 6:24–26", theme: "The Priestly Aaronic Blessing", isNew: true },
  { num: 6, ref: "Deuteronomy 14:2", theme: "Chosen People & Consecrated Identity", isNew: false },
  { num: 7, ref: "Deuteronomy 29:9", theme: "Covenant Diligence & Good Prosperity", isNew: false },
  { num: 8, ref: "Deuteronomy 30:16", theme: "Loving God & Walking in His Ways", isNew: false },
  { num: 9, ref: "Deuteronomy 30:19", theme: "Choose Life & Covenant Blessing", isNew: false },
  { num: 10, ref: "Deuteronomy 32:4", theme: "The Rock of Absolute Truth & Justice", isNew: false },
  { num: 11, ref: "Deuteronomy 32:30", theme: "Supernatural Momentum in God", isNew: false },
  { num: 12, ref: "Joshua 1:8", theme: "Meditation on Scripture & Good Success", isNew: false },
  { num: 13, ref: "Joshua 1:9", theme: "Holy Courage: The Lord is With You", isNew: false },
  { num: 14, ref: "2 Chronicles 7:14", theme: "Humility, Prayer & National Revival", isNew: false },
  { num: 15, ref: "2 Chronicles 15:2", theme: "Seeking God Wholeheartedly", isNew: false },
  { num: 16, ref: "Nehemiah 8:10", theme: "The Joy of the LORD is Your Strength", isNew: false },
  { num: 17, ref: "1 Samuel 16:7", theme: "God Looks on the Pure Heart", isNew: true },
  { num: 18, ref: "1 Samuel 30:8", theme: "Pursue, Overtake & Recover All", isNew: false },
  { num: 19, ref: "Job 1:1", theme: "Integrity, Uprightness & Fearing God", isNew: false },
  { num: 20, ref: "Job 19:25", theme: "I Know That My Redeemer Liveth", isNew: false },
  { num: 21, ref: "Job 32:8–9", theme: "The Inspiration of the Almighty", isNew: false },
  { num: 22, ref: "Psalm 4:8", theme: "Peaceful Sleep in Divine Safety", isNew: false },
  { num: 23, ref: "Psalm 8:4", theme: "Crown of Glory & Human Value", isNew: false },
  { num: 24, ref: "Psalm 16:5–6", theme: "Pleasant Places & Goodly Heritage", isNew: false },
  { num: 25, ref: "Psalm 16:8", theme: "The Lord at My Right Hand", isNew: false },
  { num: 26, ref: "Psalm 19:7", theme: "The Law of the Lord Converting the Soul", isNew: false },
  { num: 27, ref: "Psalm 25:4–5", theme: "Leading in Truth & Daily Paths", isNew: false },
  { num: 28, ref: "Psalm 25:5", theme: "Waiting on the God of Salvation", isNew: false },
  { num: 29, ref: "Psalm 25:8–9", theme: "Guiding the Meek in Judgment", isNew: false },
  { num: 30, ref: "Psalm 25:14–15", theme: "The Secret of the Lord & His Covenant", isNew: false },
  { num: 31, ref: "Psalm 25:15", theme: "Eyes Continually Toward the Lord", isNew: false },
  { num: 32, ref: "Psalm 25:20", theme: "Delivering the Soul From Shame", isNew: false },
  { num: 33, ref: "Psalm 33:18", theme: "The Eye of the Lord Upon His Saints", isNew: false },
  { num: 34, ref: "Psalm 37:4", theme: "Delight in the Lord & Heart Desires", isNew: false },
  { num: 35, ref: "Psalm 37:21", theme: "Righteous Generosity & Mercy", isNew: false },
  { num: 36, ref: "Psalm 37:23", theme: "Steps of a Good Man Ordered by the Lord", isNew: false },
  { num: 37, ref: "Psalm 37:28", theme: "Forsaketh Not His Saints Forever", isNew: false },
  { num: 38, ref: "Psalm 42:2", theme: "Thirsting for the Living God", isNew: false },
  { num: 39, ref: "Psalm 51:1–2", theme: "Tender Mercies & Inner Cleansing", isNew: false },
  { num: 40, ref: "Psalm 51:11", theme: "Take Not Thy Holy Spirit From Me", isNew: false },
  { num: 41, ref: "Psalm 52:8", theme: "Green Olive Tree in God's House", isNew: false },
  { num: 42, ref: "Psalm 62:11", theme: "Power Belongeth Unto God", isNew: false },
  { num: 43, ref: "Psalm 62:11–12", theme: "Power & Mercy Belong to the Sovereign Lord", isNew: false },
  { num: 44, ref: "Psalm 63:1", theme: "Early Will I Seek Thee in Thirst", isNew: false },
  { num: 45, ref: "Psalm 67:7", theme: "God Blessing Us to the Earth's Ends", isNew: false },
  { num: 46, ref: "Psalm 73:25", theme: "Whom Have I in Heaven But Thee", isNew: false },
  { num: 47, ref: "Psalm 81:10", theme: "Open Thy Mouth Wide & I Will Fill It", isNew: false },
  { num: 48, ref: "Psalm 82:5", theme: "Deliverance from Darkness & Blindness", isNew: false },
  { num: 49, ref: "Psalm 82:6–7", theme: "Awakening to Royal Spiritual Identity", isNew: false },
  { num: 50, ref: "Psalm 84:10", theme: "A Day in Thy Courts is Better Than a Thousand", isNew: false },
  { num: 51, ref: "Psalm 90:4", theme: "A Thousand Years in God's Sight", isNew: false },
  { num: 52, ref: "Psalm 91:4", theme: "Covering Under His Wings & Feathers", isNew: false },
  { num: 53, ref: "Psalm 91:7–8", theme: "Ten Thousand at Thy Right Hand", isNew: false },
  { num: 54, ref: "Psalm 92:12", theme: "Flourishing Like the Palm Tree & Cedar", isNew: false },
  { num: 55, ref: "Psalm 94:19", theme: "Comforts Delighting the Soul in Thoughts", isNew: false },
  { num: 56, ref: "Psalm 103:1", theme: "Bless the Lord, O My Soul", isNew: false },
  { num: 57, ref: "Psalm 103:1–2", theme: "Forget Not All His Benefits", isNew: false },
  { num: 58, ref: "Psalm 103:2", theme: "Grateful Heart & Divine Remembrance", isNew: false },
  { num: 59, ref: "Psalm 103:12", theme: "Transgressions Removed as East from West", isNew: false },
  { num: 60, ref: "Psalm 110:1", theme: "Sit at My Right Hand Until Enemies Made Footstool", isNew: false },
  { num: 61, ref: "Psalm 112:1–2", theme: "Mighty on Earth: The Generation of the Upright", isNew: false },
  { num: 62, ref: "Psalm 112:6–7", theme: "Unshakeable Trust: Not Afraid of Evil Tidings", isNew: false },
  { num: 63, ref: "Psalm 119:9–11", theme: "Cleansing the Young Life by God's Word", isNew: false },
  { num: 64, ref: "Psalm 119:10–11", theme: "Seeking with the Whole Heart", isNew: false },
  { num: 65, ref: "Psalm 119:11", theme: "Thy Word Have I Hid in Mine Heart", isNew: false },
  { num: 66, ref: "Psalm 119:105", theme: "A Lamp Unto My Feet & Light Unto My Path", isNew: false },
  { num: 67, ref: "Psalm 119:130", theme: "The Entrance of Thy Words Giveth Light", isNew: false },
  { num: 68, ref: "Psalm 121:7–8", theme: "The Lord Shall Preserve Thy Going Out & Coming In", isNew: false },
  { num: 69, ref: "Psalm 130:3–5", theme: "Plenteous Forgiveness & Waiting on the Lord", isNew: false },
  { num: 70, ref: "Psalm 138:6", theme: "Respect Unto the Lowly & Humble", isNew: false },
  { num: 71, ref: "Psalm 143:10", theme: "Teach Me to Do Thy Will, for Thou Art My God", isNew: false },
  { num: 72, ref: "Proverbs 1:26", theme: "The Fear of the Lord & True Wisdom", isNew: false },
  { num: 73, ref: "Proverbs 3:5–6", theme: "Trust in the Lord with All Thine Heart", isNew: false },
  { num: 74, ref: "Proverbs 3:34", theme: "Grace Unto the Lowly & Scorn to Scorners", isNew: false },
  { num: 75, ref: "Proverbs 8:13", theme: "Fearing the Lord is to Hate Evil & Pride", isNew: false },
  { num: 76, ref: "Proverbs 11:31", theme: "Righteous Recompense in the Earth", isNew: false },
  { num: 77, ref: "Proverbs 13:20–21", theme: "Walking with Wise Men to Be Wise", isNew: false },
  { num: 78, ref: "Proverbs 14:26", theme: "In the Fear of the Lord is Strong Confidence", isNew: false },
  { num: 79, ref: "Proverbs 19:1", theme: "Better is the Poor Who Walks in Integrity", isNew: false },
  { num: 80, ref: "Proverbs 19:21", theme: "The Counsel of the Lord Shall Stand", isNew: false },
  { num: 81, ref: "Proverbs 24:3–4", theme: "Through Wisdom a House is Builded", isNew: false },
  { num: 82, ref: "Proverbs 24:16", theme: "A Just Man Falleth Seven Times and Riseth Up", isNew: false },
  { num: 83, ref: "Proverbs 25:28", theme: "Rule Over One's Own Spirit", isNew: false },
  { num: 84, ref: "Proverbs 31:30", theme: "A Woman That Feareth the Lord Shall Be Praised", isNew: true },
  { num: 85, ref: "Ecclesiastes 3:11", theme: "Everything Beautiful in His Time", isNew: false },
  { num: 86, ref: "Ecclesiastes 3:12–13", theme: "Rejoicing & Doing Good in Life", isNew: false },
  { num: 87, ref: "Ecclesiastes 4:12", theme: "A Threefold Cord is Not Quickly Broken", isNew: false },
  { num: 88, ref: "Ecclesiastes 7:10", theme: "Wisdom Concerning the Former Days", isNew: false },
  { num: 89, ref: "Ecclesiastes 7:29", theme: "God Made Man Upright", isNew: false },
  { num: 90, ref: "Ecclesiastes 9:11", theme: "The Race is Not to the Swift, But God's Grace", isNew: false },
  { num: 91, ref: "Ecclesiastes 12:13–14", theme: "Fear God & Keep His Commandments", isNew: false },
  { num: 92, ref: "Isaiah 3:10", theme: "Say Ye to the Righteous: It Shall Be Well With Him", isNew: false },
  { num: 93, ref: "Isaiah 26:3–4", theme: "Perfect Peace Whose Mind is Stayed on Thee", isNew: false },
  { num: 94, ref: "Isaiah 40:31", theme: "Renewing Strength Like Eagles", isNew: true },
  { num: 95, ref: "Isaiah 41:10", theme: "Fear Thou Not, For I Am with Thee", isNew: false },
  { num: 96, ref: "Isaiah 45:2", theme: "Breaking Gates of Brass & Cutting Bars of Iron", isNew: false },
  { num: 97, ref: "Isaiah 53:5", theme: "By His Stripes We Are Healed", isNew: false },
  { num: 98, ref: "Isaiah 54:8", theme: "With Everlasting Kindness Will I Have Mercy", isNew: false },
  { num: 99, ref: "Isaiah 55:11", theme: "God's Word Prospering Whereto It Was Sent", isNew: false },
  { num: 100, ref: "Isaiah 64:4", theme: "God Acting on Behalf of Him That Waiteth", isNew: false },
  { num: 101, ref: "Jeremiah 6:16", theme: "Ask for the Old Paths & Good Way", isNew: false },
  { num: 102, ref: "Jeremiah 9:23–24", theme: "Glorying in Knowing and Understanding God", isNew: false },
  { num: 103, ref: "Jeremiah 17:7", theme: "Blessed is the Man That Trusteth in the Lord", isNew: false },
  { num: 104, ref: "Jeremiah 30:17", theme: "I Will Restore Health Unto Thee", isNew: false },
  { num: 105, ref: "Lamentations 3:22–23", theme: "His Mercies Are New Every Morning", isNew: false },
  { num: 106, ref: "Lamentations 3:25", theme: "The Lord is Good to Them That Wait for Him", isNew: false },
  { num: 107, ref: "Lamentations 3:37", theme: "Who is He That Saith and It Cometh to Pass", isNew: false },
  { num: 108, ref: "Ezekiel 22:30", theme: "Standing in the Gap for the Land", isNew: false },
  { num: 109, ref: "Daniel 11:32", theme: "The People That Do Know Their God Shall Be Strong", isNew: false },
  { num: 110, ref: "Obadiah 1:17", theme: "Deliverance on Mount Zion & Possessing Possessions", isNew: false },
  { num: 111, ref: "Amos 5:24", theme: "Let Judgment Run Down as Waters", isNew: false },
  { num: 112, ref: "Micah 5:2", theme: "Ruler in Israel From Days of Eternity", isNew: false },
  { num: 113, ref: "Micah 5:9", theme: "Thine Hand Lifted Up Upon Thine Adversaries", isNew: false },
  { num: 114, ref: "Micah 6:8", theme: "To Do Justly, Love Mercy & Walk Humbly", isNew: false },
  { num: 115, ref: "Micah 7:7–8", theme: "Rejoice Not Against Me: When I Fall, I Shall Arise", isNew: false },
  { num: 116, ref: "Micah 7:19", theme: "Casting All Sins Into the Depths of the Sea", isNew: false },
  { num: 117, ref: "Habakkuk 2:2–3", theme: "Write the Vision & Make It Plain", isNew: false },
  { num: 118, ref: "Habakkuk 2:3", theme: "Though the Vision Tarry, Wait for It", isNew: false },
  { num: 119, ref: "Zephaniah 3:17", theme: "The Lord in Thy Midst Rejoicing Over Thee with Joy", isNew: false },
  { num: 120, ref: "Zechariah 4:6", theme: "Not by Might Nor Power, But by My Spirit", isNew: false },
  { num: 121, ref: "Zechariah 4:9", theme: "His Hands Laid the Foundation & His Hands Shall Finish It", isNew: true },
  { num: 122, ref: "Malachi 2:2", theme: "Giving Glory Unto My Name", isNew: true },
  { num: 123, ref: "Malachi 4:2", theme: "The Sun of Righteousness Arising with Healing in His Wings", isNew: false },

  // NT (124-307)
  { num: 124, ref: "Matthew 5:14–16", theme: "Ye Are the Light of the World", isNew: false },
  { num: 125, ref: "Matthew 10:28", theme: "Fear Not Them Which Kill the Body", isNew: true },
  { num: 126, ref: "Matthew 11:12", theme: "The Kingdom of Heaven Suffereth Violence", isNew: false },
  { num: 127, ref: "Matthew 11:29–30", theme: "Take My Yoke Upon You & Learn of Me", isNew: true },
  { num: 128, ref: "Matthew 23:12", theme: "Whosoever Exalteth Himself Shall Be Abased", isNew: false },
  { num: 129, ref: "Mark 11:24", theme: "What Things Soever Ye Desire When Ye Pray", isNew: true },
  { num: 130, ref: "Luke 4:18", theme: "The Spirit of the Lord is Upon Me", isNew: true },
  { num: 131, ref: "Luke 11:34–36", theme: "The Light of the Body is the Eye", isNew: false },
  { num: 132, ref: "Luke 12:32", theme: "Fear Not, Little Flock: The Kingdom is Given", isNew: true },
  { num: 133, ref: "Luke 16:9", theme: "Faithful Stewards & Eternal Dwellings", isNew: true },
  { num: 134, ref: "Luke 16:15", theme: "God Knoweth Your Hearts", isNew: false },
  { num: 135, ref: "John 1:14", theme: "The Word Was Made Flesh & Dwelt Among Us", isNew: false },
  { num: 136, ref: "John 3:16", theme: "God So Loved the World", isNew: false },
  { num: 137, ref: "John 7:17", theme: "Doing His Will to Know the Doctrine", isNew: false },
  { num: 138, ref: "John 14:3", theme: "I Go to Prepare a Place for You", isNew: false },
  { num: 139, ref: "John 14:6", theme: "I Am the Way, the Truth, and the Life", isNew: false },
  { num: 140, ref: "John 15:4", theme: "Abide in Me, and I in You", isNew: false },
  { num: 141, ref: "John 15:7", theme: "Ask What Ye Will & It Shall Be Done", isNew: false },
  { num: 142, ref: "John 16:23–24", theme: "Ask in My Name That Your Joy May Be Full", isNew: false },
  { num: 143, ref: "John 16:33", theme: "Be of Good Cheer: I Have Overcome the World", isNew: false },
  { num: 144, ref: "John 21:15–25", theme: "Feed My Sheep & Follow Thou Me", isNew: false },
  { num: 145, ref: "Acts 16:31", theme: "Believe on the Lord Jesus Christ & Thou Shalt Be Saved", isNew: false },
  { num: 146, ref: "Acts 17:28", theme: "In Him We Live, and Move, and Have Our Being", isNew: false },
  { num: 147, ref: "Acts 20:24", theme: "Finishing My Course with Joy", isNew: false },
  { num: 148, ref: "Romans 1:20", theme: "Eternal Power & Godhead Clearly Seen", isNew: false },
  { num: 149, ref: "Romans 1:24,26", theme: "Purifying the Soul from Carnal Passions", isNew: false },
  { num: 150, ref: "Romans 2:6–7", theme: "Patient Continuance in Well Doing", isNew: false },
  { num: 151, ref: "Romans 2:29", theme: "Circumcision of the Heart in the Spirit", isNew: false },
  { num: 152, ref: "Romans 3:20", theme: "Justified Freely by His Grace", isNew: false },
  { num: 153, ref: "Romans 5:8", theme: "God Commendeth His Love Toward Us", isNew: false },
  { num: 154, ref: "Romans 8:18", theme: "Suffering Not Worthy to Be Compared to Future Glory", isNew: false },
  { num: 155, ref: "Romans 8:19", theme: "Creation Waiting for Manifestation of Sons of God", isNew: false },
  { num: 156, ref: "Romans 8:26", theme: "The Spirit Helpeth Our Infirmities with Groanings", isNew: false },
  { num: 157, ref: "Romans 8:29–30", theme: "Conformed to the Image of His Son", isNew: false },
  { num: 158, ref: "Romans 9:16", theme: "Not of Him That Willeth, But of God That Sheweth Mercy", isNew: true },
  { num: 159, ref: "Romans 10:15", theme: "How Beautiful Are the Feet of Them That Preach the Gospel", isNew: false },
  { num: 160, ref: "Romans 11:34–36", theme: "For of Him, and Through Him, and to Him, Are All Things", isNew: true },
  { num: 161, ref: "Romans 12:2", theme: "Transformed by the Renewing of Your Mind", isNew: false },
  { num: 162, ref: "Romans 12:9", theme: "Abhor That Which is Evil; Cleave to That Which is Good", isNew: false },
  { num: 163, ref: "Romans 12:12", theme: "Rejoicing in Hope; Patient in Tribulation; Instant in Prayer", isNew: false },
  { num: 164, ref: "Romans 12:14–16", theme: "Bless Them Which Persecute You: Bless, and Curse Not", isNew: false },
  { num: 165, ref: "Romans 12:16", theme: "Be of the Same Mind One Toward Another", isNew: false },
  { num: 166, ref: "Romans 12:16–18", theme: "Provide Things Honest in the Sight of All Men", isNew: false },
  { num: 167, ref: "Romans 12:18", theme: "As Much as Lieth in You, Live Peaceably with All Men", isNew: false },
  { num: 168, ref: "Romans 12:19", theme: "Vengeance is Mine; I Will Repay, Saith the Lord", isNew: false },
  { num: 169, ref: "Romans 15:13", theme: "The God of Hope Fill You with All Joy & Peace", isNew: false },
  { num: 170, ref: "1 Corinthians 1:25", theme: "The Foolishness of God is Wiser Than Men", isNew: false },
  { num: 171, ref: "1 Corinthians 2:12", theme: "Receiving the Spirit Which is of God to Know His Gifts", isNew: false },
  { num: 172, ref: "1 Corinthians 2:16", theme: "We Have the Mind of Christ", isNew: false },
  { num: 173, ref: "1 Corinthians 4:7", theme: "What Hast Thou That Thou Didst Not Receive?", isNew: false },
  { num: 174, ref: "1 Corinthians 6:9–10", theme: "Washed, Sanctified, and Justified in the Spirit", isNew: false },
  { num: 175, ref: "1 Corinthians 8:6", theme: "One God the Father, and One Lord Jesus Christ", isNew: false },
  { num: 176, ref: "1 Corinthians 9:24–25", theme: "Running the Race to Obtain an Incorruptible Crown", isNew: false },
  { num: 177, ref: "1 Corinthians 10:13", theme: "No Temptation Taken You But Such as is Common to Man", isNew: false },
  { num: 178, ref: "1 Corinthians 15:57", theme: "Thanks Be to God Which Giveth Us the Victory", isNew: false },
  { num: 179, ref: "1 Corinthians 15:58", theme: "Steadfast, Unmoveable, Always Abounding in the Work", isNew: false },
  { num: 180, ref: "2 Corinthians 1:10", theme: "Delivered from Great Death & Delivering Still", isNew: false },
  { num: 181, ref: "2 Corinthians 4:7", theme: "Treasure in Earthen Vessels", isNew: false },
  { num: 182, ref: "2 Corinthians 4:8–9", theme: "Troubled on Every Side, Yet Not Distressed", isNew: false },
  { num: 183, ref: "2 Corinthians 4:17", theme: "Our Light Affliction Worketh an Eternal Weight of Glory", isNew: false },
  { num: 184, ref: "2 Corinthians 4:18", theme: "Looking Not at the Things Which Are Seen", isNew: false },
  { num: 185, ref: "2 Corinthians 5:16", theme: "Knowing No Man After the Flesh", isNew: false },
  { num: 186, ref: "2 Corinthians 5:16–21", theme: "A New Creature in Christ Jesus", isNew: false },
  { num: 187, ref: "2 Corinthians 5:18", theme: "The Ministry of Reconciliation", isNew: false },
  { num: 188, ref: "2 Corinthians 5:21", theme: "Made the Righteousness of God in Him", isNew: false },
  { num: 189, ref: "2 Corinthians 7:1", theme: "Perfecting Holiness in the Fear of God", isNew: false },
  { num: 190, ref: "2 Corinthians 8:12", theme: "Accepted According to That a Man Hath", isNew: false },
  { num: 191, ref: "2 Corinthians 9:8", theme: "God is Able to Make All Grace Abound Toward You", isNew: false },
  { num: 192, ref: "2 Corinthians 10:4", theme: "Mighty Through God to Pulling Down Strongholds", isNew: false },
  { num: 193, ref: "2 Corinthians 10:17–18", theme: "He That Glorieth, Let Him Glory in the Lord", isNew: false },
  { num: 194, ref: "2 Corinthians 12:9", theme: "My Grace is Sufficient for Thee", isNew: false },
  { num: 195, ref: "2 Corinthians 13:7", theme: "Doing No Evil: Walking in Integrity", isNew: false },
  { num: 196, ref: "2 Corinthians 13:11", theme: "Be Perfect, Be of Good Comfort, Be of One Mind", isNew: false },
  { num: 197, ref: "Galatians 3:26–27", theme: "Children of God by Faith in Christ Jesus", isNew: false },
  { num: 198, ref: "Galatians 4:6", theme: "The Spirit of His Son Crying, Abba, Father", isNew: false },
  { num: 199, ref: "Galatians 5:22–23", theme: "The Ninefold Fruit of the Spirit", isNew: false },
  { num: 200, ref: "Ephesians 1:7", theme: "Redemption Through His Blood & Forgiveness of Sins", isNew: false },
  { num: 201, ref: "Ephesians 1:18", theme: "Eyes of Your Understanding Being Enlightened", isNew: false },
  { num: 202, ref: "Ephesians 2:8", theme: "By Grace Are Ye Saved Through Faith", isNew: false },
  { num: 203, ref: "Ephesians 2:10", theme: "His Workmanship Created Unto Good Works", isNew: false },
  { num: 204, ref: "Ephesians 3:20–21", theme: "Able to Do Exceeding Abundantly Above All We Ask", isNew: false },
  { num: 205, ref: "Ephesians 5:3–4", theme: "Walking in Purity & Consecration", isNew: false },
  { num: 206, ref: "Ephesians 5:15–17", theme: "Walk Circumspectly, Redeeming the Time", isNew: false },
  { num: 207, ref: "Ephesians 5:19", theme: "Speaking to Yourselves in Psalms and Hymns", isNew: false },
  { num: 208, ref: "Ephesians 5:19–20", theme: "Giving Thanks Always for All Things", isNew: false },
  { num: 209, ref: "Ephesians 5:21", theme: "Submitting Yourselves One to Another in the Fear of God", isNew: false },
  { num: 210, ref: "Ephesians 6:7–8", theme: "Doing Service As to the Lord, and Not to Men", isNew: false },
  { num: 211, ref: "Ephesians 6:10", theme: "Be Strong in the Lord and the Power of His Might", isNew: false },
  { num: 212, ref: "Ephesians 6:15", theme: "Feet Shod with Preparation of the Gospel of Peace", isNew: false },
  { num: 213, ref: "Ephesians 6:19", theme: "Utterance Given to Make Known Mystery of Gospel", isNew: false },
  { num: 214, ref: "Philippians 2:3–4", theme: "In Lowliness of Mind Esteeming Other Better", isNew: true },
  { num: 215, ref: "Philippians 2:5", theme: "Let This Mind Be in You Which Was in Christ Jesus", isNew: false },
  { num: 216, ref: "Philippians 2:5–11", theme: "The Humble Servant Exalted Above Every Name", isNew: false },
  { num: 217, ref: "Philippians 2:9", theme: "A Name Which is Above Every Name", isNew: true },
  { num: 218, ref: "Philippians 2:12", theme: "Work Out Your Own Salvation with Fear & Trembling", isNew: false },
  { num: 219, ref: "Philippians 2:14–16", theme: "Do All Things Without Murmurings and Disputings", isNew: true },
  { num: 220, ref: "Philippians 3:10", theme: "That I May Know Him and Power of His Resurrection", isNew: true },
  { num: 221, ref: "Philippians 3:13–14", theme: "Pressing Toward the Mark for the Prize", isNew: false },
  { num: 222, ref: "Philippians 4:6–7", theme: "Be Careful for Nothing: The Peace That Passeth Knowledge", isNew: false },
  { num: 223, ref: "Philippians 4:8", theme: "Think on These Things: Pure, Lovely, Good Report", isNew: false },
  { num: 224, ref: "Philippians 4:19", theme: "My God Shall Supply All Your Need", isNew: true },
  { num: 225, ref: "Colossians 1:15–20", theme: "Image of the Invisible God, Firstborn of Creation", isNew: false },
  { num: 226, ref: "Colossians 1:26–27", theme: "Christ in You, the Hope of Glory", isNew: false },
  { num: 227, ref: "Colossians 2:6–7", theme: "Rooted and Built Up in Him, Abounding in Thanksgiving", isNew: false },
  { num: 228, ref: "Colossians 2:16–17", theme: "Shadow of Things to Come; Body is of Christ", isNew: false },
  { num: 229, ref: "Colossians 3:12–15", theme: "Put on Bowels of Mercies, Kindness & Forgiveness", isNew: false },
  { num: 230, ref: "Colossians 3:16", theme: "Let the Word of Christ Dwell in You Richly", isNew: false },
  { num: 231, ref: "Colossians 3:17", theme: "Whatsoever Ye Do, Do All in the Name of Jesus", isNew: false },
  { num: 232, ref: "Colossians 3:23", theme: "Do It Heartily, As to the Lord, and Not Unto Men", isNew: false },
  { num: 233, ref: "Colossians 4:5–6", theme: "Let Your Speech Be Always with Grace, Seasoned with Salt", isNew: false },
  { num: 234, ref: "1 Thessalonians 1:5", theme: "Gospel Came in Power, and in the Holy Ghost", isNew: false },
  { num: 235, ref: "1 Thessalonians 3:12–13", theme: "Abound in Love to Unblameable Holiness", isNew: false },
  { num: 236, ref: "1 Thessalonians 5:1–11", theme: "Children of the Light & Not of the Darkness", isNew: false },
  { num: 237, ref: "1 Thessalonians 5:6", theme: "Let Us Watch and Be Sober", isNew: false },
  { num: 238, ref: "1 Thessalonians 5:16–18", theme: "Rejoice Evermore, Pray Without Ceasing, In Every Thing Give Thanks", isNew: false },
  { num: 239, ref: "1 Thessalonians 5:23", theme: "Sanctify You Wholly: Spirit, Soul, and Body", isNew: false },
  { num: 240, ref: "2 Thessalonians 2:10–12", theme: "Love of the Truth That Ye Might Be Saved", isNew: false },
  { num: 241, ref: "2 Thessalonians 3:16", theme: "The Lord of Peace Give You Peace Always by All Means", isNew: false },
  { num: 242, ref: "1 Timothy 1:12–14", theme: "Counted Faithful, Putting Me into the Ministry", isNew: false },
  { num: 243, ref: "1 Timothy 4:12", theme: "Be Thou an Example of the Believers", isNew: false },
  { num: 244, ref: "1 Timothy 6:12", theme: "Fight the Good Fight of Faith, Lay Hold on Eternal Life", isNew: false },
  { num: 245, ref: "2 Timothy 1:7", theme: "Spirit of Power, Love, and of a Sound Mind", isNew: false },
  { num: 246, ref: "2 Timothy 1:9", theme: "Called with an Holy Calling According to Purpose & Grace", isNew: false },
  { num: 247, ref: "2 Timothy 1:11–12", theme: "I Know Whom I Have Believed & Am Persuaded", isNew: false },
  { num: 248, ref: "2 Timothy 1:12", theme: "He is Able to Keep That Which I Have Committed", isNew: false },
  { num: 249, ref: "2 Timothy 2:4–5", theme: "A Soldier Not Entangling in Affairs of This Life", isNew: false },
  { num: 250, ref: "2 Timothy 2:15", theme: "Study to Shew Thyself Approved Unto God", isNew: false },
  { num: 251, ref: "2 Timothy 2:23–24", theme: "Gentle Unto All Men, Apt to Teach, Patient", isNew: false },
  { num: 252, ref: "2 Timothy 3:12", theme: "Living Godly in Christ Jesus", isNew: false },
  { num: 253, ref: "2 Timothy 3:16–17", theme: "All Scripture is Given by Inspiration of God", isNew: false },
  { num: 254, ref: "Titus 2:11–12", theme: "Grace Teaching Us to Live Soberly, Righteously, and Godly", isNew: false },
  { num: 255, ref: "Hebrews 2:10–12", theme: "Captain of Our Salvation Made Perfect", isNew: false },
  { num: 256, ref: "Hebrews 2:11", theme: "He is Not Ashamed to Call Them Brethren", isNew: false },
  { num: 257, ref: "Hebrews 3:13", theme: "Exhort One Another Daily While It is Called To Day", isNew: false },
  { num: 258, ref: "Hebrews 4:12", theme: "The Word of God is Quick, and Powerful, and Sharper", isNew: false },
  { num: 259, ref: "Hebrews 4:14–16", theme: "Great High Priest Passed into the Heavens", isNew: true },
  { num: 260, ref: "Hebrews 4:16", theme: "Come Boldly Unto the Throne of Grace", isNew: false },
  { num: 261, ref: "Hebrews 6:10", theme: "God is Not Unrighteous to Forget Your Work and Labour of Love", isNew: false },
  { num: 262, ref: "Hebrews 9:28", theme: "Christ Was Once Offered to Bear the Sins of Many", isNew: false },
  { num: 263, ref: "Hebrews 10:24", theme: "Consider One Another to Provoke Unto Love & Good Works", isNew: false },
  { num: 264, ref: "Hebrews 10:25", theme: "Not Forsaking the Assembling of Ourselves Together", isNew: false },
  { num: 265, ref: "Hebrews 11:6–7", theme: "He That Cometh to God Must Believe That He Is", isNew: false },
  { num: 266, ref: "Hebrews 12:1–2", theme: "Looking Unto Jesus the Author & Finisher of Our Faith", isNew: false },
  { num: 267, ref: "Hebrews 13:5–6", theme: "I Will Never Leave Thee, Nor Forsake Thee", isNew: false },
  { num: 268, ref: "Hebrews 13:20–21", theme: "The God of Peace Make You Perfect in Every Good Work", isNew: false },
  { num: 269, ref: "James 1:2–3", theme: "Count It All Joy When Ye Fall into Divers Temptations", isNew: false },
  { num: 270, ref: "James 1:12", theme: "Blessed is the Man That Endureth Temptation", isNew: false },
  { num: 271, ref: "James 1:13–14", theme: "God Cannot Be Tempted with Evil", isNew: false },
  { num: 272, ref: "James 1:17", theme: "Every Good Gift and Every Perfect Gift is from Above", isNew: false },
  { num: 273, ref: "James 1:19–20", theme: "Swift to Hear, Slow to Speak, Slow to Wrath", isNew: false },
  { num: 274, ref: "James 4:7", theme: "Submit Yourselves Therefore to God; Resist the Devil", isNew: false },
  { num: 275, ref: "James 5:16", theme: "The Effectual Fervent Prayer of a Righteous Man Availeth Much", isNew: false },
  { num: 276, ref: "1 Peter 1:3–4", theme: "Begotten Again Unto a Lively Hope by Resurrection", isNew: false },
  { num: 277, ref: "1 Peter 1:15–16", theme: "Be Ye Holy; For I Am Holy", isNew: false },
  { num: 278, ref: "1 Peter 1:22–25", theme: "Being Born Again by the Incorruptible Word of God", isNew: false },
  { num: 279, ref: "1 Peter 1:23", theme: "The Word of God Which Liveth and Abideth For Ever", isNew: false },
  { num: 280, ref: "1 Peter 2:2–3", theme: "As Newborn Babes Desire Sincere Milk of the Word", isNew: false },
  { num: 281, ref: "1 Peter 2:17", theme: "Honour All Men. Love the Brotherhood. Fear God.", isNew: false },
  { num: 282, ref: "1 Peter 3:3–4", theme: "Ornament of a Meek and Quiet Spirit", isNew: false },
  { num: 283, ref: "1 Peter 3:10–11", theme: "He That Will Love Life and See Good Days", isNew: false },
  { num: 284, ref: "1 Peter 3:12", theme: "Eyes of the Lord Over the Righteous, Ears Open to Prayers", isNew: false },
  { num: 285, ref: "1 Peter 3:13", theme: "Who is He That Will Harm You If Ye Followers of Good?", isNew: false },
  { num: 286, ref: "1 Peter 3:15", theme: "Sanctify the Lord God in Your Hearts: Ready to Give Answer", isNew: false },
  { num: 287, ref: "1 Peter 4:7", theme: "End of All Things is at Hand: Watch Unto Prayer", isNew: false },
  { num: 288, ref: "1 Peter 5:7", theme: "Casting All Your Care Upon Him; For He Careth for You", isNew: false },
  { num: 289, ref: "1 Peter 5:10", theme: "God of All Grace Make You Perfect, Stablish, Strengthen, Settle You", isNew: false },
  { num: 290, ref: "2 Peter 1:3–4", theme: "Given Unto Us All Things That Pertain Unto Life & Godliness", isNew: false },
  { num: 291, ref: "2 Peter 1:16", theme: "Eyewitnesses of His Majesty", isNew: false },
  { num: 292, ref: "2 Peter 3:9", theme: "The Lord is Longsuffering to Us-Ward, Not Willing Any Perish", isNew: false },
  { num: 293, ref: "1 John 1:5–7", theme: "Walk in the Light, As He is in the Light", isNew: false },
  { num: 294, ref: "1 John 2:2", theme: "Propitiation for Our Sins & for the Whole World", isNew: false },
  { num: 295, ref: "1 John 2:15", theme: "Love Not the World, Neither the Things in the World", isNew: false },
  { num: 296, ref: "1 John 4:4", theme: "Greater is He That is in You Than He in the World", isNew: false },
  { num: 297, ref: "1 John 5:14–15", theme: "Confidence That If We Ask According to His Will He Heareth Us", isNew: false },
  { num: 298, ref: "Jude 1:20", theme: "Building Up Yourselves on Most Holy Faith, Praying in Holy Ghost", isNew: false },
  { num: 299, ref: "Jude 1:20–22", theme: "Keep Yourselves in the Love of God, Having Compassion", isNew: false },
  { num: 300, ref: "Jude 1:24–25", theme: "Able to Keep You from Falling, and to Present You Faultless", isNew: false },
  { num: 301, ref: "Revelation 1:18", theme: "I Am He That Liveth, and Was Dead; Alive for Evermore", isNew: false },
  { num: 302, ref: "Revelation 3:11", theme: "Hold That Fast Which Thou Hast, That No Man Take Thy Crown", isNew: false },
  { num: 303, ref: "Revelation 3:17", theme: "Riches in Christ Beyond Earthly Complacency", isNew: false },
  { num: 304, ref: "Revelation 3:21", theme: "To Him That Overcometh Will I Grant to Sit with Me in My Throne", isNew: false },
  { num: 305, ref: "Revelation 5:13", theme: "Blessing, Honour, Glory, and Power Unto the Lamb", isNew: false },
  { num: 306, ref: "Revelation 7:16–17", theme: "God Shall Wipe Away All Tears from Their Eyes", isNew: false },
  { num: 307, ref: "Revelation 21:6", theme: "It is Done: I Am Alpha and Omega, the Beginning and the End", isNew: false }
];

console.log(`Loaded ${RAW_SCRIPTURES.length} raw author scriptures.`);

module.exports = RAW_SCRIPTURES;
