// Complete Accurate KJV Texts for Author's 307 Favourite Scriptures
// Mapped by reference

module.exports = {
  // OT (1-50)
  "Genesis 1:28": "And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it: and have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that moveth upon the earth.",
  "Exodus 19:5": "Now therefore, if ye will obey my voice indeed, and keep my covenant, then ye shall be a peculiar treasure unto me above all people: for all the earth is mine.",
  "Exodus 33:14": "And he said, My presence shall go with thee, and I will give thee rest.",
  "Leviticus 5:17": "And if a soul sin, and commit any of these things which are forbidden to be done by the commandments of the LORD; though he wist it not, yet is he guilty, and shall bear his iniquity.",
  "Numbers 6:24–26": "The LORD bless thee, and keep thee: The LORD make his face shine upon thee, and be gracious unto thee: The LORD lift up his countenance upon thee, and give thee peace.",
  "Deuteronomy 14:2": "For thou art an holy people unto the LORD thy God, and the LORD hath chosen thee to be a peculiar people unto himself, above all the nations that are upon the earth.",
  "Deuteronomy 29:9": "Keep therefore the words of this covenant, and do them, that ye may prosper in all that ye do.",
  "Deuteronomy 30:16": "In that I command thee this day to love the LORD thy God, to walk in his ways, and to keep his commandments and his statutes and his judgments, that thou mayest live and multiply: and the LORD thy God shall bless thee in the land whither thou goest to possess it.",
  "Deuteronomy 30:19": "I call heaven and earth to record this day against you, that I have set before you life and death, blessing and cursing: therefore choose life, that both thou and thy seed may live.",
  "Deuteronomy 32:4": "He is the Rock, his work is perfect: for all his ways are judgment: a God of truth and without iniquity, just and right is he.",
  "Deuteronomy 32:30": "How should one chase a thousand, and two put ten thousand to flight, except their Rock had sold them, and the LORD had shut them up?",
  "Joshua 1:8": "This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.",
  "Joshua 1:9": "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
  "2 Chronicles 7:14": "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land.",
  "2 Chronicles 15:2": "And he went out to meet Asa, and said unto him, Hear ye me, Asa, and all Judah and Benjamin; The LORD is with you, while ye be with him; and if ye seek him, he will be found of you; but if ye forsake him, he will forsake you.",
  "Nehemiah 8:10": "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength.",
  "1 Samuel 16:7": "But the LORD said unto Samuel, Look not on his countenance, or on the height of his stature; because I have refused him: for the LORD seeth not as man seeth; for man looketh on the outward appearance, but the LORD looketh on the heart.",
  "1 Samuel 30:8": "And David enquired at the LORD, saying, Shall I pursue after this troop? shall I overtake them? And he answered him, Pursue: for thou shalt surely overtake them, and without fail recover all.",
  "Job 1:1": "There was a man in the land of Uz, whose name was Job; and that man was perfect and upright, and one that feared God, and eschewed evil.",
  "Job 19:25": "For I know that my redeemer liveth, and that he shall stand at the latter day upon the earth.",
  "Job 32:8–9": "But there is a spirit in man: and the inspiration of the Almighty giveth them understanding. Great men are not always wise: neither do the aged understand judgment.",
  "Psalm 4:8": "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.",
  "Psalm 8:4": "What is man, that thou art mindful of him? and the son of man, that thou visitest him?",
  "Psalm 16:5–6": "The LORD is the portion of mine inheritance and of my cup: thou maintainest my lot. The lines are fallen unto me in pleasant places; yea, I have a goodly heritage.",
  "Psalm 16:8": "I have set the LORD always before me: because he is at my right hand, I shall not be moved.",
  "Psalm 19:7": "The law of the LORD is perfect, converting the soul: the testimony of the LORD is sure, making wise the simple.",
  "Psalm 25:4–5": "Shew me thy ways, O LORD; teach me thy paths. Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day.",
  "Psalm 25:5": "Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day.",
  "Psalm 25:8–9": "Good and upright is the LORD: therefore will he teach sinners in the way. The meek will he guide in judgment: and the meek will he teach his way.",
  "Psalm 25:14–15": "The secret of the LORD is with them that fear him; and he will shew them his covenant. Mine eyes are ever toward the LORD; for he shall pluck my feet out of the net.",
  "Psalm 25:15": "Mine eyes are ever toward the LORD; for he shall pluck my feet out of the net.",
  "Psalm 25:20": "O keep my soul, and deliver me: let me not be ashamed; for I put my trust in thee.",
  "Psalm 33:18": "Behold, the eye of the LORD is upon them that fear him, upon them that hope in his mercy.",
  "Psalm 37:4": "Delight thyself also in the LORD; and he shall give thee the desires of thine heart.",
  "Psalm 37:21": "The wicked borroweth, and payeth not again: but the righteous sheweth mercy, and giveth.",
  "Psalm 37:23": "The steps of a good man are ordered by the LORD: and he delighteth in his way.",
  "Psalm 37:28": "For the LORD loveth judgment, and forsaketh not his saints; they are preserved for ever: but the seed of the wicked shall be cut off.",
  "Psalm 42:2": "My soul thirsteth for God, for the living God: when shall I come and appear before God?",
  "Psalm 51:1–2": "Have mercy upon me, O God, according to thy lovingkindness: according unto the multitude of thy tender mercies blot out my transgressions. Wash me throughly from mine iniquity, and cleanse me from my sin.",
  "Psalm 51:11": "Cast me not away from thy presence; and take not thy holy spirit from me.",
  "Psalm 52:8": "But I am like a green olive tree in the house of God: I trust in the mercy of God for ever and ever.",
  "Psalm 62:11": "God hath spoken once; twice have I heard this; that power belongeth unto God.",
  "Psalm 62:11–12": "God hath spoken once; twice have I heard this; that power belongeth unto God. Also unto thee, O Lord, belongeth mercy: for thou renderest to every man according to his work.",
  "Psalm 63:1": "O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is.",
  "Psalm 67:7": "God shall bless us; and all the ends of the earth shall fear him.",
  "Psalm 73:25": "Whom have I in heaven but thee? and there is none upon earth that I desire beside thee.",
  "Psalm 81:10": "I am the LORD thy God, which brought thee out of the land of Egypt: open thy mouth wide, and I will fill it.",
  "Psalm 82:5": "They know not, neither will they understand; they walk on in darkness: all the foundations of the earth are out of course.",
  "Psalm 82:6–7": "I have said, Ye are gods; and all of you are children of the most High. But ye shall die like men, and fall like one of the princes.",
  "Psalm 84:10": "For a day in thy courts is better than a thousand. I had rather be a doorkeeper in the house of my God, than to dwell in the tents of wickedness.",
  "Psalm 90:4": "For a thousand years in thy sight are but as yesterday when it is past, and as a watch in the night.",
  "Psalm 91:4": "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler.",
  "Psalm 91:7–8": "A thousand shall fall at thy side, and ten thousand at thy right hand; but it shall not come nigh thee. Only with thine eyes shalt thou behold and see the reward of the wicked.",
  "Psalm 92:12": "The righteous shall flourish like the palm tree: he shall grow like a cedar in Lebanon.",
  "Psalm 94:19": "In the multitude of my thoughts within me thy comforts delight my soul.",
  "Psalm 103:1": "Bless the LORD, O my soul: and all that is within me, bless his holy name.",
  "Psalm 103:1–2": "Bless the LORD, O my soul: and all that is within me, bless his holy name. Bless the LORD, O my soul, and forget not all his benefits.",
  "Psalm 103:2": "Bless the LORD, O my soul, and forget not all his benefits.",
  "Psalm 103:12": "As far as the east is from the west, so far hath he removed our transgressions from us.",
  "Psalm 110:1": "The LORD said unto my Lord, Sit thou at my right hand, until I make thine enemies thy footstool.",
  "Psalm 112:1–2": "Praise ye the LORD. Blessed is the man that feareth the LORD, that delighteth greatly in his commandments. His seed shall be mighty upon earth: the generation of the upright shall be blessed.",
  "Psalm 112:6–7": "Surely he shall not be moved for ever: the righteous shall be in everlasting remembrance. He shall not be afraid of evil tidings: his heart is fixed, trusting in the LORD.",
  "Psalm 119:9–11": "Wherewithal shall a young man cleanse his way? by taking heed thereto according to thy word. With my whole heart have I sought thee: O let me not wander from thy commandments. Thy word have I hid in mine heart, that I might not sin against thee.",
  "Psalm 119:10–11": "With my whole heart have I sought thee: O let me not wander from thy commandments. Thy word have I hid in mine heart, that I might not sin against thee.",
  "Psalm 119:11": "Thy word have I hid in mine heart, that I might not sin against thee.",
  "Psalm 119:105": "Thy word is a lamp unto my feet, and a light unto my path.",
  "Psalm 119:130": "The entrance of thy words giveth light; it giveth understanding unto the simple.",
  "Psalm 121:7–8": "The LORD shall preserve thee from all evil: he shall preserve thy soul. The LORD shall preserve thy going out and thy coming in from this time forth, and even for evermore.",
  "Psalm 130:3–5": "If thou, LORD, shouldest mark iniquities, O Lord, who shall stand? But there is forgiveness with thee, that thou mayest be feared. I wait for the LORD, my soul doth wait, and in his word do I hope.",
  "Psalm 138:6": "Though the LORD be high, yet hath he respect unto the lowly: but the proud he knoweth afar off.",
  "Psalm 143:10": "Teach me to do thy will; for thou art my God: thy spirit is good; lead me into the land of uprightness.",
  "Proverbs 1:26": "I also will laugh at your calamity; I will mock when your fear cometh.",
  "Proverbs 3:5–6": "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",
  "Proverbs 3:34": "Surely he scorneth the scorners: but he giveth grace unto the lowly.",
  "Proverbs 8:13": "The fear of the LORD is to hate evil: pride, and arrogancy, and the evil way, and the froward mouth, do I hate.",
  "Proverbs 11:31": "Behold, the righteous shall be recompensed in the earth: much more the wicked and the sinner.",
  "Proverbs 13:20–21": "He that walketh with wise men shall be wise: but a companion of fools shall be destroyed. Evil pursueth sinners: but to the righteous good shall be repayed.",
  "Proverbs 14:26": "In the fear of the LORD is strong confidence: and his children shall have a place of refuge.",
  "Proverbs 19:1": "Better is the poor that walketh in his integrity, than he that is perverse in his lips, and is a fool.",
  "Proverbs 19:21": "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand.",
  "Proverbs 24:3–4": "Through wisdom is an house builded; and by understanding it is established: And by knowledge shall the chambers be filled with all precious and pleasant riches.",
  "Proverbs 24:16": "For a just man falleth seven times, and riseth up again: but the wicked shall fall into mischief.",
  "Proverbs 25:28": "He that hath no rule over his own spirit is like a city that is broken down, and without walls.",
  "Proverbs 31:30": "Favour is deceitful, and beauty is vain: but a woman that feareth the LORD, she shall be praised.",
  "Ecclesiastes 3:11": "He hath made every thing beautiful in his time: also he hath set the world in their heart, so that no man can find out the work that God maketh from the beginning to the end.",
  "Ecclesiastes 3:12–13": "I know that there is no good in them, but for a man to rejoice, and to do good in his life. And also that every man should eat and drink, and enjoy the good of all his labour, it is the gift of God.",
  "Ecclesiastes 4:12": "And if one prevail against him, two shall withstand him; and a threefold cord is not quickly broken.",
  "Ecclesiastes 7:10": "Say not thou, What is the cause that the former days were better than these? for thou dost not enquire wisely concerning this.",
  "Ecclesiastes 7:29": "Lo, this only have I found, that God hath made man upright; but they have sought out many inventions.",
  "Ecclesiastes 9:11": "I returned, and saw under the sun, that the race is not to the swift, nor the battle to the strong, neither yet bread to the wise, nor yet riches to men of understanding, nor yet favour to men of skill; but time and chance happeneth to them all.",
  "Ecclesiastes 12:13–14": "Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the whole duty of man. For God shall bring every work into judgment, with every secret thing, whether it be good, or whether it be evil.",
  "Isaiah 3:10": "Say ye to the righteous, that it shall be well with him: for they shall eat the fruit of their doings.",
  "Isaiah 26:3–4": "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee. Trust ye in the LORD for ever: for in the LORD JEHOVAH is everlasting strength.",
  "Isaiah 40:31": "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
  "Isaiah 41:10": "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
  "Isaiah 45:2": "I will go before thee, and make the crooked places straight: I will break in pieces the gates of brass, and cut in sunder the bars of iron.",
  "Isaiah 53:5": "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.",
  "Isaiah 54:8": "In a little wrath I hid my face from thee for a moment; but with everlasting kindness will I have mercy on thee, saith the LORD thy Redeemer.",
  "Isaiah 55:11": "So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it.",
  "Isaiah 64:4": "For since the beginning of the world men have not heard, nor perceived by the ear, neither hath the eye seen, O God, beside thee, what he hath prepared for him that waiteth for him.",
  "Jeremiah 6:16": "Thus saith the LORD, Stand ye in the ways, and see, and ask for the old paths, where is the good way, and walk therein, and ye shall find rest for your souls.",
  "Jeremiah 9:23–24": "Thus saith the LORD, Let not the wise man glory in his wisdom, neither let the mighty man glory in his might, let not the rich man glory in his riches: But let him that glorieth glory in this, that he understandeth and knoweth me, that I am the LORD which exercise lovingkindness, judgment, and righteousness, in the earth.",
  "Jeremiah 17:7": "Blessed is the man that trusteth in the LORD, and whose hope the LORD is.",
  "Jeremiah 30:17": "For I will restore health unto thee, and I will heal thee of thy wounds, saith the LORD; because they called thee an Outcast, saying, This is Zion, whom no man seeketh after.",
  "Lamentations 3:22–23": "It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.",
  "Lamentations 3:25": "The LORD is good unto them that wait for him, to the soul that seeketh him.",
  "Lamentations 3:37": "Who is he that saith, and it cometh to pass, when the Lord commandeth it not?",
  "Ezekiel 22:30": "And I sought for a man among them, that should make up the hedge, and stand in the gap before me for the land, that I should not destroy it: but I found none.",
  "Daniel 11:32": "And such as do wickedly against the covenant shall he corrupt by flatteries: but the people that do know their God shall be strong, and do exploits.",
  "Obadiah 1:17": "But upon mount Zion shall be deliverance, and there shall be holiness; and the house of Jacob shall possess their possessions.",
  "Amos 5:24": "But let judgment run down as waters, and righteousness as a mighty stream.",
  "Micah 5:2": "But thou, Bethlehem Ephratah, though thou be little among the thousands of Judah, yet out of thee shall he come forth unto me that is to be ruler in Israel; whose goings forth have been from of old, from everlasting.",
  "Micah 5:9": "Thine hand shall be lifted up upon thine adversaries, and all thine enemies shall be cut off.",
  "Micah 6:8": "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?",
  "Micah 7:7–8": "Therefore I will look unto the LORD; I will wait for the God of my salvation: my God will hear me. Rejoice not against me, O mine enemy: when I fall, I shall arise; when I sit in darkness, the LORD shall be a light unto me.",
  "Micah 7:19": "He will turn again, he will have compassion upon us; he will subdue our iniquities; and thou wilt cast all their sins into the depths of the sea.",
  "Habakkuk 2:2–3": "And the LORD answered me, and said, Write the vision, and make it plain upon tables, that he may run that readeth it. For the vision is yet for an appointed time, but at the end it shall speak, and not lie: though it tarry, wait for it; because it will surely come, it will not tarry.",
  "Habakkuk 2:3": "For the vision is yet for an appointed time, but at the end it shall speak, and not lie: though it tarry, wait for it; because it will surely come, it will not tarry.",
  "Zephaniah 3:17": "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.",
  "Zechariah 4:6": "Then he answered and spake unto me, saying, This is the word of the LORD unto Zerubbabel, saying, Not by might, nor by power, but by my spirit, saith the LORD of hosts.",
  "Zechariah 4:9": "The hands of Zerubbabel have laid the foundation of this house; his hands shall also finish it; and thou shalt know that the LORD of hosts hath sent me unto you.",
  "Malachi 2:2": "If ye will not hear, and if ye will not lay it to heart, to give glory unto my name, saith the LORD of hosts, I will even send a curse upon you, and I will curse your blessings.",
  "Malachi 4:2": "But unto you that fear my name shall the Sun of righteousness arise with healing in his wings; and ye shall go forth, and grow up as calves of the stall.",

  // NT (124-307)
  "Matthew 5:14–16": "Ye are the light of the world. A city that is set on an hill cannot be hid. Neither do men light a candle, and put it under a bushel, but on a candlestick; and it giveth light unto all that are in the house. Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.",
  "Matthew 10:28": "And fear not them which kill the body, but are not able to kill the soul: but rather fear him which is able to destroy both soul and body in hell.",
  "Matthew 11:12": "And from the days of John the Baptist until now the kingdom of heaven suffereth violence, and the violent take it by force.",
  "Matthew 11:29–30": "Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. For my yoke is easy, and my burden is light.",
  "Matthew 23:12": "And whosoever shall exalt himself shall be abased; and he that shall humble himself shall be exalted.",
  "Mark 11:24": "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.",
  "Luke 4:18": "The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor; he hath sent me to heal the brokenhearted, to preach deliverance to the captives, and recovering of sight to the blind, to set at liberty them that are bruised.",
  "Luke 11:34–36": "The light of the body is the eye: therefore when thine eye is single, thy whole body also is full of light; but when thine eye is evil, thy body also is full of darkness.",
  "Luke 12:32": "Fear not, little flock; for it is your Father's good pleasure to give you the kingdom.",
  "Luke 16:9": "And I say unto you, Make to yourselves friends of the mammon of unrighteousness; that, when ye fail, they may receive you into everlasting habitations.",
  "Luke 16:15": "And he said unto them, Ye are they which justify yourselves before men; but God knoweth your hearts: for that which is highly esteemed among men is abomination in the sight of God.",
  "John 1:14": "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth.",
  "John 3:16": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
  "John 7:17": "If any man will do his will, he shall know of the doctrine, whether it be of God, or whether I speak of myself.",
  "John 14:3": "And if I go and prepare a place for you, I will come again, and receive you unto myself; that where I am, there ye may be also.",
  "John 14:6": "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.",
  "John 15:4": "Abide in me, and I in you. As the branch cannot bear fruit of itself, except it abide in the vine; no more can ye, except ye abide in me.",
  "John 15:7": "If ye abide in me, and my words abide in you, ye shall ask what ye will, and it shall be done unto you.",
  "John 16:23–24": "Verily, verily, I say unto you, Whatsoever ye shall ask the Father in my name, he will give it you. Hitherto have ye asked nothing in my name: ask, and ye shall receive, that your joy may be full.",
  "John 16:33": "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.",
  "John 21:15–25": "He saith unto him, Feed my lambs... Follow thou me.",
  "Acts 16:31": "And they said, Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house.",
  "Acts 17:28": "For in him we live, and move, and have our being; as certain also of your own poets have said, For we are also his offspring.",
  "Acts 20:24": "But none of these things move me, neither count I my life dear unto myself, so that I might finish my course with joy, and the ministry, which I have received of the Lord Jesus, to testify the gospel of the grace of God.",
  "Romans 1:20": "For the invisible things of him from the creation of the world are clearly seen, being understood by the things that are made, even his eternal power and Godhead; so that they are without excuse.",
  "Romans 1:24,26": "Wherefore God also gave them up to uncleanness... For this cause God gave them up unto vile affections.",
  "Romans 2:6–7": "Who will render to every man according to his deeds: To them who by patient continuance in well doing seek for glory and honour and immortality, eternal life.",
  "Romans 2:29": "But he is a Jew, which is one inwardly; and circumcision is that of the heart, in the spirit, and not in the letter; whose praise is not of men, but of God.",
  "Romans 3:20": "Therefore by the deeds of the law there shall no flesh be justified in his sight: for by the law is the knowledge of sin.",
  "Romans 5:8": "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.",
  "Romans 8:18": "For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us.",
  "Romans 8:19": "For the earnest expectation of the creature waiteth for the manifestation of the sons of God.",
  "Romans 8:26": "Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us with groanings which cannot be uttered.",
  "Romans 8:29–30": "For whom he did foreknow, he also did predestinate to be conformed to the image of his Son... Moreover whom he did predestinate, them he also called: and whom he called, them he also justified: and whom he justified, them he also glorified.",
  "Romans 9:16": "So then it is not of him that willeth, nor of him that runneth, but of God that sheweth mercy.",
  "Romans 10:15": "And how shall they preach, except they be sent? as it is written, How beautiful are the feet of them that preach the gospel of peace, and bring glad tidings of good things!",
  "Romans 11:34–36": "For who hath known the mind of the Lord? or who hath been his counsellor? Or who hath first given to him, and it shall be recompensed unto him again? For of him, and through him, and to him, are all things: to whom be glory for ever. Amen.",
  "Romans 12:2": "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.",
  "Romans 12:9": "Let love be without dissimulation. Abhor that which is evil; cleave to that which is good.",
  "Romans 12:12": "Rejoicing in hope; patient in tribulation; continuing instant in prayer.",
  "Romans 12:14–16": "Bless them which persecute you: bless, and curse not. Rejoice with them that do rejoice, and weep with them that weep. Be of the same mind one toward another.",
  "Romans 12:16": "Be of the same mind one toward another. Mind not high things, but condescend to men of low estate. Be not wise in your own conceits.",
  "Romans 12:16–18": "Recompense to no man evil for evil. Provide things honest in the sight of all men. If it be possible, as much as lieth in you, live peaceably with all men.",
  "Romans 12:18": "If it be possible, as much as lieth in you, live peaceably with all men.",
  "Romans 12:19": "Dearly beloved, avenge not yourselves, but rather give place unto wrath: for it is written, Vengeance is mine; I will repay, saith the Lord.",
  "Romans 15:13": "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
  "1 Corinthians 1:25": "Because the foolishness of God is wiser than men; and the weakness of God is stronger than men.",
  "1 Corinthians 2:12": "Now we have received, not the spirit of the world, but the spirit which is of God; that we might know the things that are freely given to us of God.",
  "1 Corinthians 2:16": "For who hath known the mind of the Lord, that he may instruct him? But we have the mind of Christ.",
  "1 Corinthians 4:7": "For who maketh thee to differ from another? and what hast thou that thou didst not receive? now if thou didst receive it, why dost thou glory, as if thou hadst not received it?",
  "1 Corinthians 6:9–10": "Know ye not that the unrighteous shall not inherit the kingdom of God?",
  "1 Corinthians 8:6": "But to us there is but one God, the Father, of whom are all things, and we in him; and one Lord Jesus Christ, by whom are all things, and we by him.",
  "1 Corinthians 9:24–25": "Know ye not that they which run in a race run all, but one receiveth the prize? So run, that ye may obtain. And every man that striveth for the mastery is temperate in all things. Now they do it to obtain a corruptible crown; but we an incorruptible.",
  "1 Corinthians 10:13": "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it.",
  "1 Corinthians 15:57": "But thanks be to God, which giveth us the victory through our Lord Jesus Christ.",
  "1 Corinthians 15:58": "Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord.",
  "2 Corinthians 1:10": "Who delivered us from so great a death, and doth deliver: in whom we trust that he will yet deliver us.",
  "2 Corinthians 4:7": "But we have this treasure in earthen vessels, that the excellency of the power may be of God, and not of us.",
  "2 Corinthians 4:8–9": "We are troubled on every side, yet not distressed; we are perplexed, but not in despair; Persecuted, but not forsaken; cast down, but not destroyed.",
  "2 Corinthians 4:17": "For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory.",
  "2 Corinthians 4:18": "While we look not at the things which are seen, but at the things which are not seen: for the things which are seen are temporal; but the things which are not seen are eternal.",
  "2 Corinthians 5:16": "Wherefore henceforth know we no man after the flesh: yea, though we have known Christ after the flesh, yet now henceforth know we him no more.",
  "2 Corinthians 5:16–21": "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new... For he hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him.",
  "2 Corinthians 5:18": "And all things are of God, who hath reconciled us to himself by Jesus Christ, and hath given to us the ministry of reconciliation.",
  "2 Corinthians 5:21": "For he hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him.",
  "2 Corinthians 7:1": "Having therefore these promises, dearly beloved, let us cleanse ourselves from all filthiness of the flesh and spirit, perfecting holiness in the fear of God.",
  "2 Corinthians 8:12": "For if there be first a willing mind, it is accepted according to that a man hath, and not according to that he hath not.",
  "2 Corinthians 9:8": "And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work.",
  "2 Corinthians 10:4": "(For the weapons of our warfare are not carnal, but mighty through God to the pulling down of strong holds;)",
  "2 Corinthians 10:17–18": "But he that glorieth, let him glory in the Lord. For not he that commendeth himself is approved, but whom the Lord commendeth.",
  "2 Corinthians 12:9": "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.",
  "2 Corinthians 13:7": "Now I pray to God that ye do no evil; not that we should appear approved, but that ye should do that which is honest.",
  "2 Corinthians 13:11": "Finally, brethren, farewell. Be perfect, be of good comfort, be of one mind, live in peace; and the God of love and peace shall be with you.",
  "Galatians 3:26–27": "For ye are all the children of God by faith in Christ Jesus. For as many of you as have been baptized into Christ have put on Christ.",
  "Galatians 4:6": "And because ye are sons, God hath sent forth the Spirit of his Son into your hearts, crying, Abba, Father.",
  "Galatians 5:22–23": "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, Meekness, temperance: against such there is no law.",
  "Ephesians 1:7": "In whom we have redemption through his blood, the forgiveness of sins, according to the riches of his grace.",
  "Ephesians 1:18": "The eyes of your understanding being enlightened; that ye may know what is the hope of his calling, and what the riches of the glory of his inheritance in the saints.",
  "Ephesians 2:8": "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.",
  "Ephesians 2:10": "For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.",
  "Ephesians 3:20–21": "Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us, Unto him be glory in the church by Christ Jesus throughout all ages, world without end. Amen.",
  "Ephesians 5:3–4": "But fornication, and all uncleanness, or covetousness, let it not be once named among you, as becometh saints; Neither filthiness, nor foolish talking, nor jesting, which are not convenient: but rather giving of thanks.",
  "Ephesians 5:15–17": "See then that ye walk circumspectly, not as fools, but as wise, Redeeming the time, because the days are evil. Wherefore be ye not unwise, but understanding what the will of the Lord is.",
  "Ephesians 5:19": "Speaking to yourselves in psalms and hymns and spiritual songs, singing and making melody in your heart to the Lord.",
  "Ephesians 5:19–20": "Speaking to yourselves in psalms and hymns and spiritual songs, singing and making melody in your heart to the Lord; Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ.",
  "Ephesians 5:21": "Submitting yourselves one to another in the fear of God.",
  "Ephesians 6:7–8": "With good will doing service, as to the Lord, and not to men: Knowing that whatsoever good thing any man doeth, the same shall he receive of the Lord, whether he be bond or free.",
  "Ephesians 6:10": "Finally, my brethren, be strong in the Lord, and in the power of his might.",
  "Ephesians 6:15": "And your feet shod with the preparation of the gospel of peace.",
  "Ephesians 6:19": "And for me, that utterance may be given unto me, that I may open my mouth boldly, to make known the mystery of the gospel.",
  "Philippians 2:3–4": "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves. Look not every man on his own things, but every man also on the things of others.",
  "Philippians 2:5": "Let this mind be in you, which was also in Christ Jesus.",
  "Philippians 2:5–11": "Who, being in the form of God, thought it not robbery to be equal with God: But made himself of no reputation, and took upon him the form of a servant... Wherefore God also hath highly exalted him, and given him a name which is above every name.",
  "Philippians 2:9": "Wherefore God also hath highly exalted him, and given him a name which is above every name.",
  "Philippians 2:12": "Wherefore, my beloved, as ye have always obeyed, not as in my presence only, but now much more in my absence, work out your own salvation with fear and trembling.",
  "Philippians 2:14–16": "Do all things without murmurings and disputings: That ye may be blameless and harmless, the sons of God, without rebuke, in the midst of a crooked and perverse nation, among whom ye shine as lights in the world; Holding forth the word of life.",
  "Philippians 3:10": "That I may know him, and the power of his resurrection, and the fellowship of his sufferings, being made conformable unto his death.",
  "Philippians 3:13–14": "Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before, I press toward the mark for the prize of the high calling of God in Christ Jesus.",
  "Philippians 4:6–7": "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
  "Philippians 4:8": "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.",
  "Philippians 4:19": "But my God shall supply all your need according to his riches in glory by Christ Jesus.",
  "Colossians 1:15–20": "Who is the image of the invisible God, the firstborn of every creature: For by him were all things created, that are in heaven, and that are in earth... And he is before all things, and by him all things consist.",
  "Colossians 1:26–27": "Even the mystery which hath been hid from ages and from generations, but now is made manifest to his saints: To whom God would make known what is the riches of the glory of this mystery among the Gentiles; which is Christ in you, the hope of glory.",
  "Colossians 2:6–7": "As ye have therefore received Christ Jesus the Lord, so walk ye in him: Rooted and built up in him, and stablished in the faith, as ye have been taught, abounding therein with thanksgiving.",
  "Colossians 2:16–17": "Let no man therefore judge you in meat, or in drink, or in respect of an holyday, or of the new moon, or of the sabbath days: Which are a shadow of things to come; but the body is of Christ.",
  "Colossians 3:12–15": "Put on therefore, as the elect of God, holy and beloved, bowels of mercies, kindness, humbleness of mind, meekness, longsuffering; Forbearing one another, and forgiving one another... And above all these things put on charity, which is the bond of perfectness.",
  "Colossians 3:16": "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord.",
  "Colossians 3:17": "And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him.",
  "Colossians 3:23": "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.",
  "Colossians 4:5–6": "Walk in wisdom toward them that are without, redeeming the time. Let your speech be alway with grace, seasoned with salt, that ye may know how ye ought to answer every man.",
  "1 Thessalonians 1:5": "For our gospel came not unto you in word only, but also in power, and in the Holy Ghost, and in much assurance.",
  "1 Thessalonians 3:12–13": "And the Lord make you to increase and abound in love one toward another, and toward all men... To the end he may stablish your hearts unblameable in holiness before God.",
  "1 Thessalonians 5:1–11": "Ye are all the children of light, and the children of the day: we are not of the night, nor of darkness.",
  "1 Thessalonians 5:6": "Therefore let us not sleep, as do others; but let us watch and be sober.",
  "1 Thessalonians 5:16–18": "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you.",
  "1 Thessalonians 5:23": "And the very God of peace sanctify you wholly; and I pray God your whole spirit and soul and body be preserved blameless unto the coming of our Lord Jesus Christ.",
  "2 Thessalonians 2:10–12": "Because they received not the love of the truth, that they might be saved.",
  "2 Thessalonians 3:16": "Now the Lord of peace himself give you peace always by all means. The Lord be with you all.",
  "1 Timothy 1:12–14": "And I thank Christ Jesus our Lord, who hath enabled me, for that he counted me faithful, putting me into the ministry.",
  "1 Timothy 4:12": "Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity.",
  "1 Timothy 6:12": "Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called, and hast professed a good profession before many witnesses.",
  "2 Timothy 1:7": "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
  "2 Timothy 1:9": "Who hath saved us, and called us with an holy calling, not according to our works, but according to his own purpose and grace, which was given us in Christ Jesus before the world began.",
  "2 Timothy 1:11–12": "For the which cause I also suffer these things: nevertheless I am not ashamed: for I know whom I have believed, and am persuaded that he is able to keep that which I have committed unto him against that day.",
  "2 Timothy 1:12": "For I know whom I have believed, and am persuaded that he is able to keep that which I have committed unto him against that day.",
  "2 Timothy 2:4–5": "No man that warreth entangleth himself with the affairs of this life; that he may please him who hath chosen him to be a soldier. And if a man also strive for masteries, yet is he not crowned, except he strive lawfully.",
  "2 Timothy 2:15": "Study to shew thyself approved unto God, a workman that needeth not to be ashamed, rightly dividing the word of truth.",
  "2 Timothy 2:23–24": "But foolish and unlearned questions avoid, knowing that they do gender strifes. And the servant of the Lord must not strive; but be gentle unto all men, apt to teach, patient.",
  "2 Timothy 3:12": "Yea, and all that will live godly in Christ Jesus shall suffer persecution.",
  "2 Timothy 3:16–17": "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness: That the man of God may be perfect, throughly furnished unto all good works.",
  "Titus 2:11–12": "For the grace of God that bringeth salvation hath appeared to all men, Teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously, and godly, in this present world.",
  "Hebrews 2:10–12": "For it became him, for whom are all things, and by whom are all things, in bringing many sons unto glory, to make the captain of their salvation perfect through sufferings.",
  "Hebrews 2:11": "For both he that sanctifieth and they who are sanctified are all of one: for which cause he is not ashamed to call them brethren.",
  "Hebrews 3:13": "But exhort one another daily, while it is called To day; lest any of you be hardened through the deceitfulness of sin.",
  "Hebrews 4:12": "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart.",
  "Hebrews 4:14–16": "Seeing then that we have a great high priest, that is passed into the heavens, Jesus the Son of God, let us hold fast our profession. For we have not an high priest which cannot be touched with the feeling of our infirmities; but was in all points tempted like as we are, yet without sin. Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.",
  "Hebrews 4:16": "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.",
  "Hebrews 6:10": "For God is not unrighteous to forget your work and labour of love, which ye have shewed toward his name, in that ye have ministered to the saints, and do minister.",
  "Hebrews 9:28": "So Christ was once offered to bear the sins of many; and unto them that look for him shall he appear the second time without sin unto salvation.",
  "Hebrews 10:24": "And let us consider one another to provoke unto love and to good works.",
  "Hebrews 10:25": "Not forsaking the assembling of ourselves together, as the manner of some is; but exhorting one another: and so much the more, as ye see the day approaching.",
  "Hebrews 11:6–7": "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.",
  "Hebrews 12:1–2": "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, Looking unto Jesus the author and finisher of our faith.",
  "Hebrews 13:5–6": "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee. So that we may boldly say, The Lord is my helper, and I will not fear what man shall do unto me.",
  "Hebrews 13:20–21": "Now the God of peace, that brought again from the dead our Lord Jesus, that great shepherd of the sheep, through the blood of the everlasting covenant, Make you perfect in every good work to do his will, working in you that which is wellpleasing in his sight, through Jesus Christ.",
  "James 1:2–3": "My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience.",
  "James 1:12": "Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him.",
  "James 1:13–14": "Let no man say when he is tempted, I am tempted of God: for God cannot be tempted with evil, neither tempteth he any man: But every man is tempted, when he is drawn away of his own lust, and enticed.",
  "James 1:17": "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning.",
  "James 1:19–20": "Wherefore, my beloved brethren, let every man be swift to hear, slow to speak, slow to wrath: For the wrath of man worketh not the righteousness of God.",
  "James 4:7": "Submit yourselves therefore to God. Resist the devil, and he will flee from you.",
  "James 5:16": "Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.",
  "1 Peter 1:3–4": "Blessed be the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead, To an inheritance incorruptible, and undefiled, and that fadeth not away, reserved in heaven for you.",
  "1 Peter 1:15–16": "But as he which hath called you is holy, so be ye holy in all manner of conversation; Because it is written, Be ye holy; for I am holy.",
  "1 Peter 1:22–25": "Being born again, not of corruptible seed, but of incorruptible, by the word of God, which liveth and abideth for ever.",
  "1 Peter 1:23": "Being born again, not of corruptible seed, but of incorruptible, by the word of God, which liveth and abideth for ever.",
  "1 Peter 2:2–3": "As newborn babes, desire the sincere milk of the word, that ye may grow thereby: If so be ye have tasted that the Lord is gracious.",
  "1 Peter 2:17": "Honour all men. Love the brotherhood. Fear God. Honour the king.",
  "1 Peter 3:3–4": "Whose adorning let it not be that outward adorning... But let it be the hidden man of the heart, in that which is not corruptible, even the ornament of a meek and quiet spirit, which is in the sight of God of great price.",
  "1 Peter 3:10–11": "For he that will love life, and see good days, let him refrain his tongue from evil, and his lips that they speak no guile: Let him eschew evil, and do good; let him seek peace, and ensue it.",
  "1 Peter 3:12": "For the eyes of the Lord are over the righteous, and his ears are open unto their prayers: but the face of the Lord is against them that do evil.",
  "1 Peter 3:13": "And who is he that will harm you, if ye be followers of that which is good?",
  "1 Peter 3:15": "But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear.",
  "1 Peter 4:7": "But the end of all things is at hand: be ye therefore sober, and watch unto prayer.",
  "1 Peter 5:7": "Casting all your care upon him; for he careth for you.",
  "1 Peter 5:10": "But the God of all grace, who hath called us unto his eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you.",
  "2 Peter 1:3–4": "According as his divine power hath given unto us all things that pertain unto life and godliness, through the knowledge of him that hath called us to glory and virtue: Whereby are given unto us exceeding great and precious promises.",
  "2 Peter 1:16": "For we have not followed cunningly devised fables, when we made known unto you the power and coming of our Lord Jesus Christ, but were eyewitnesses of his majesty.",
  "2 Peter 3:9": "The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance.",
  "1 John 1:5–7": "This then is the message which we have heard of him, and declare unto you, that God is light, and in him is no darkness at all. If we say that we have fellowship with him, and walk in darkness, we lie, and do not the truth: But if we walk in the light, as he is in the light, we have fellowship one with another, and the blood of Jesus Christ his Son cleanseth us from all sin.",
  "1 John 2:2": "And he is the propitiation for our sins: and not for ours only, but also for the sins of the whole world.",
  "1 John 2:15": "Love not the world, neither the things that are in the world. If any man love the world, the love of the Father is not in him.",
  "1 John 4:4": "Ye are of God, little children, and have overcome them: because greater is he that is in you, than he that is in the world.",
  "1 John 5:14–15": "And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us: And if we know that he hear us, whatsoever we ask, we know that we have the petitions that we desired of him.",
  "Jude 1:20": "But ye, beloved, building up yourselves on your most holy faith, praying in the Holy Ghost.",
  "Jude 1:20–22": "But ye, beloved, building up yourselves on your most holy faith, praying in the Holy Ghost, Keep yourselves in the love of God, looking for the mercy of our Lord Jesus Christ unto eternal life. And of some have compassion, making a difference.",
  "Jude 1:24–25": "Now unto him that is able to keep you from falling, and to present you faultless before the presence of his glory with exceeding joy, To the only wise God our Saviour, be glory and majesty, dominion and power, both now and ever. Amen.",
  "Revelation 1:18": "I am he that liveth, and was dead; and, behold, I am alive for evermore, Amen; and have the keys of hell and of death.",
  "Revelation 3:11": "Behold, I come quickly: hold that fast which thou hast, that no man take thy crown.",
  "Revelation 3:17": "Because thou sayest, I am rich, and increased with goods, and have need of nothing; and knowest not that thou art wretched, and miserable, and poor, and blind, and naked.",
  "Revelation 3:21": "To him that overcometh will I grant to sit with me in my throne, even as I also overcame, and am set down with my Father in his throne.",
  "Revelation 5:13": "And every creature which is in heaven, and on the earth, and under the earth, and such as are in the sea, and all that are in them, heard I saying, Blessing, and honour, and glory, and power, be unto him that sitteth upon the throne, and unto the Lamb for ever and ever.",
  "Revelation 7:16–17": "They shall hunger no more, neither thirst any more; neither shall the sun light on them, nor any heat. For the Lamb which is in the midst of the throne shall feed them, and shall lead them unto living fountains of waters: and God shall wipe away all tears from their eyes.",
  "Revelation 21:6": "And he said unto me, It is done. I am Alpha and Omega, the beginning and the end. I will give unto him that is athirst of the fountain of the water of life freely."
};
